### ISSUE TITLE
第一个吃螃蟹，希望添加对于 PostgreSQL 数据库的支持。

### ISSUE THREAD

**Issue by Jiuyong** [siteserver/cms#1]
简单浏览下代码。
后面要往跨平台方向弄的话，希望你们可以考虑 PostgreSQL 数据库。
数据层方面，可以考虑换用 EntityFramworkCore ，这个现在也支持 PostgreSQL 数据库，也支持 MySQL 数据库。这样就不用不同的数据库需要不同的访问 SQL 实现了。（不同数据库还是会有微小差异，但真的是“微小”）
应用程序构建在 ASP.Net Core 上。
这样跨平台就完美了。

**Comment by mokecc** [comment]
构建在 ASP.Net Core +1

**Comment by starlying** [comment]
没错，我们下一步将基于ASP.NET Core对整个系统重构，支持Linux跨平台部署。
PostgreSQL支持会放到将来的开发计划里面。

**Comment by skpey** [comment]
不错呢，本来想用国外的一个系统，非常支持开源

**Comment by starlying** [comment]
已实现PostgreSQL 数据库支持
