### ISSUE TITLE
https://api.siteserver.cn/v1.1/packages?isNightly=false&version=1.7.11&%24filter=id%20in%20%27SS.CMS%27&1531454505691

### ISSUE THREAD

**Issue by spyderyang** [siteserver/cms#1038]
请教一下，在windows 2008上后台用不了报的错

**Comment by spyderyang** [comment]
https://api.siteserver.cn/v1.1/packages?isNightly=false&version=1.7.11&%24filter=id%20in%20%27SS.CMS%27&1531454505691

**Comment by ningmenglv** [comment]
麻烦问下你的辅助表功能能用么

**Comment by 17671877** [comment]
是不是服务器没法联网导致的？
