### ISSUE TITLE
子站点如何获取子级站点

### ISSUE THREAD

**Issue by BaoStorm** [siteserver/cms#108]
代码如下：
`<stl:sites SiteName="{stl.SiteName}">
      [{stl.SiteName}]({stl.SiteUrl})
</stl:sites>`
这样无法获取子级站点，必须把SiteName="{stl.SiteName}"写成SiteName="XXX"这样才能获取子级站点

**Comment by LuoZhiW** [comment]
子站点的内容如何同步主站点的内容，就是说我移动端和pc端的数据同步

**Comment by starlying** [comment]
可以使用SQL标签直接调用数据库中的内容。具体用法参考：http://stl.siteserver.cn/sqlContents/1.html
