### ISSUE TITLE
点击【内容管理】的【显示项】，提示：Server Error in Application 未将对象引用设置到对象的实例。

### ISSUE THREAD

**Issue by russellyi** [siteserver/cms#1086]
在 SiteServer.BackgroundPages.Cms.ModalSelectColumns.Page_Load(Object sender, EventArgs e)   在 System.Web.UI.Control.OnLoad(EventArgs e)   在 System.Web.UI.Control.LoadRecursive()   在 System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by starlying** [comment]
这个问题已修复，8月1日会发布新版本。
