### ISSUE TITLE
请问siteserver的商城功能和微信功能将来会开源吗？

### ISSUE THREAD

**Issue by x-manJS** [siteserver/cms#11]
或者说，近期有开源这两个模块的计划吗？

**Comment by starlying** [comment]
原有的SiteServer B2C系统由于太臃肿，将来不会维护了，商城功能我们会在现有CMS基础上逐步实现，主要是简单的购物功能
微信功能已经开源了，只是还有BUG没改，没集成到解决方案里面，我们下一步会完善微信功能并集成进来

**Comment by x-manJS** [comment]
我想源码应该是在\source\SiteServer.CMS\WeiXin，谢谢。
