### ISSUE TITLE
5.082视频上传仍然有问题

### ISSUE THREAD

**Issue by skotbenben** [siteserver/cms#116]
测试时发现编辑器内视频按钮是可以正常使用的。
编辑器上方的【插入视频】按钮仍然有问题，插入后标签不再消失，但生成页面后前台页面解析不了。

测试格式：MP4
版本：5.082

**Comment by starlying** [comment]
感谢反馈，我们查一下问题，会尽快修复。

**Comment by theme800** [comment]
如果加入自定义的视频播放代码，可以保存，生成的文件中也有也能正常播放。但二次编辑时，会把这些代码自动过滤，只剩下一个空的DIV

**Comment by starlying** [comment]
已解决，V6.1发布
