### ISSUE TITLE
不能将值 NULL 插入列 'Id'，表 'qds130042389_db.dbo.siteserver_TemplateLog'；列不允许有 Null 值。INSERT 失败。语句已终止。

### ISSUE THREAD

**Issue by cxpjazz** [siteserver/cms#1193]
null

**Comment by starlying** [comment]
表siteserver_TemplateLog的字段Id没有设置为自增长导致的，系统是升级上来的吗，手动到SQLSERVER里面设置一下。

**Comment by cxpjazz** [comment]
thanks bug is ok

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："tim "<notifications@github.com>;
发送时间：2018年8月16日(星期四) 上午9:44
收件人："siteserver/cms" <cms@noreply.github.com>;
抄送："cxpjazz "<cxpjazz@gmail.com>;"Author "<author@noreply.github.com>;
主题：Re: [siteserver/cms] 不能将值 NULL 插入列 'Id'，表 'qds130042389_db.dbo.siteserver_TemplateLog'；列不允许有 Null 值。INSERT 失败。语句已终止。 (#1193)
-----------------------------------

 
表siteserver_TemplateLog的字段Id没有设置为自增长导致的，系统是升级上来的吗，手动到SQLSERVER里面设置一下。
