### ISSUE TITLE
发表文章，写完发表提示已经成功但是并没有实际存上去

### ISSUE THREAD

**Issue by cxpjazz** [siteserver/cms#1221]
之前迁移了一下数据库，后来siteserver提示更新，就更新了一下版本，然后就出现如上问题

**Comment by cxpjazz** [comment]
之前是没有主键，现在都加了一遍主键还是不行

**Comment by starlying** [comment]
看看主键是不是设置为自增长字段了

**Comment by cxpjazz** [comment]
是的，迁移了数据库导致逐渐丢失，并且主键没有自增，已经重新设置就好了，感谢
