### ISSUE TITLE
<stl:analysis>标签无效，解析不出来，该如何解决呢

### ISSUE THREAD

**Issue by ben1289** [siteserver/cms#1256]
![default](https://user-images.githubusercontent.com/42233756/44649587-eacb6200-aa16-11e8-9d6b-8ae5e68970f9.png)

**Comment by Hanshicheng** [comment]
我也碰到很多标签解析不出来，包括评论标签和评分标签，不知道怎么回事儿

**Comment by goofy74** [comment]
是不是需要计数插件

**Comment by GreenHand-Ben** [comment]
官方参考手册说 “要使 <stl:analysis> 显示浏览量，系统必须将统计设置开启（功能管理 /流量统计管理 /修改统计设置）”。

**Comment by jiangbin4586** [comment]
新版本<stl:analysis> 标签已经取消。 基本上解析不出来的标签，貌似就都取消了或者有新的标签替换了。可惜没有出文 具体哪些取消，哪些替换了。唉

**Comment by sycwz** [comment]
关键在于新版本取消后，如何处理访问量PV的情况呢？有没有好一点的解决办法？

**Comment by starlying** [comment]
目前只能通过SS.Hits插件，能够在前台显示内容的点击量，详细的数据统计插件目前还在开发中
