### ISSUE TITLE
siteserver 生成的站点如何迁移到别的服务器？

### ISSUE THREAD

**Issue by lublues** [siteserver/cms#1331]
前提：已有一个asp的pc端站点。
我用siteserver在本地建立了一个手机端站点。
请问：

1.是否可以与pc站点公用虚拟主机空间？
2.如何迁移siteserver生成的站点内容？

**Comment by starlying** [comment]
只要虚拟主机空间支持.NET 4.5或者以上版本就可以将siteserver部署上去
从本地迁移到服务器可以通过保存站点模板的方式，报错后复制到服务器的SiteFiles/SiteTemplates文件夹下，然后再新安装的系统中新建站点时选择对应的站点模板。
