### ISSUE TITLE
栏目的内容模型为图片，则内容中上传的这些图片stl怎么取？

### ISSUE THREAD

**Issue by g1293722517** [siteserver/cms#1369]
![12](https://user-images.githubusercontent.com/18181270/45791008-43121e80-bcba-11e8-8dff-6a10bc0fdbbc.png)
![23](https://user-images.githubusercontent.com/18181270/45791009-43121e80-bcba-11e8-99f7-fcbad47b448e.jpg)

请问一下，栏目的内容模型设置为图片后，这里的图片怎么取呢？

**Comment by starlying** [comment]
需要用到<stl:photos>标签
