### ISSUE TITLE
focusViewer 标签解析无效果

### ISSUE THREAD

**Issue by Jason-mxy** [siteserver/cms#146]
<stl:focusviewer channelIndex="焦点图" width="260" height="182" theme="Style1" totalNum="5"></stl:focusviewer>
解析无效果；建议更新主题样式，目前的主题样式比较老，存在兼容性问题。

**Comment by starlying** [comment]
stl:focusviewer是由flash实现的，flash浏览器已逐渐不支持，此标签已废弃
