### ISSUE TITLE
内容编辑器上传视频问题

### ISSUE THREAD

**Issue by Jason-mxy** [siteserver/cms#15]
内容编辑器上传视频，第二次切换到HTML，上传的视频路径就没有了。

**Comment by starlying** [comment]
我们查一下是CMS的问题还是UEditor的问题，如果是UEditor的问题可能没法改

**Comment by GithubMie** [comment]
我找到了解决方法，亲测通过，你也可以试一下，原文链接：http://www.07net01.com/2016/11/1714295.html

**Comment by Jason-mxy** [comment]
问题已修复。
