### ISSUE TITLE
初步安装时，管理员填写手机号，安装成功以后，登录不上

### ISSUE THREAD

**Issue by forconz** [siteserver/cms#1535]
```
        private AdministratorInfo GetByAccount(string account)
        {
            var administratorInfo = GetByUserName(account);
            if (administratorInfo != null)
                return administratorInfo;

            if (StringUtils.IsMobile(account))
                return GetByMobile(account);

            if (StringUtils.IsEmail(account))
                GetByEmail(account);

            return null;
        }
```

把 private AdministratorInfo GetByAccount(string account) 改成上面的代码，就好了。

**Comment by forconz** [comment]
创建空站点（不使用站点模板），录入内容以后，http://localhost:9643/contents/1/1.html是空白的，预览不了

**Comment by forconz** [comment]
使用在线站点模板创建站点 出错：

错误!   在线模板获取失败：页面地址http://templates.siteserver.cn无法访问！

**Comment by forconz** [comment]
PS C:\Users\Tao> ping templates.siteserver.cn

正在 Ping zbsazu.v.bsgslb.cn [116.207.130.12] 具有 32 字节的数据:
来自 116.207.130.12 的回复: 字节=32 时间=12ms TTL=56
来自 116.207.130.12 的回复: 字节=32 时间=10ms TTL=56
来自 116.207.130.12 的回复: 字节=32 时间=13ms TTL=56
来自 116.207.130.12 的回复: 字节=32 时间=105ms TTL=56

116.207.130.12 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 10ms，最长 = 105ms，平均 = 35ms

服务器带宽不怎么样啊，我访问其它服务器都是10ms以内噢

**Comment by forconz** [comment]
PS C:\Users\Tao> tracert templates.siteserver.cn

通过最多 30 个跃点跟踪
到 zbsazu.v.bsgslb.cn [116.207.130.12] 的路由:

  1     5 ms     2 ms     2 ms  TianYi.Home [192.168.1.1]
  2     5 ms     9 ms     3 ms  100.64.0.1
  3    96 ms    12 ms     5 ms  111.175.208.133
  4    11 ms     5 ms    26 ms  111.175.212.45
  5    15 ms    12 ms    12 ms  58.50.184.22
  6     *        *        *     请求超时。
  7     *        *        *     请求超时。
  8    11 ms    10 ms    53 ms  templates.siteserver.cn [116.207.130.12]

跟踪完成。

**Comment by forconz** [comment]
58.50.184.22 湖北省宜昌市 电信，到这里以后，就挂了

**Comment by starlying** [comment]
管理员填写手机号，安装成功以后，登录不上
这个问题已解决，感谢反馈
模板下载速度的问题我们研究一下
