### ISSUE TITLE
关于表单插件 SS.Form插件 bug  

### ISSUE THREAD

**Issue by dingduv** [siteserver/cms#1537]
1、后台多个表单如何引用，没有官方文档（未找到相关文档），默认引用最后一个表单；
2、表单提交未过滤<html、<script  ,前台可提交任何形式的<html、<script  ，后台都按照<html、<script 语法显示，严重影响网站安全；
3、表单数据浏览无法关闭，
网址/SiteFiles/Plugins/SS.Form/templates/list1/index.html?siteId=****&formId=****&apiUrl=%2Fapi，任何人知道siteID、formID，无需登录管理后台，均可打开浏览表单数据，存在数据泄露风险。

**Comment by zzj19930721** [comment]
这是重大BUG啊

**Comment by zfnet0591** [comment]
可能官方对这个表单插件也还没理清楚

**Comment by starlying** [comment]
我们仔细研究一下，会尽快修复

**Comment by starlying** [comment]
1、后台多个表单如何引用，没有官方文档（未找到相关文档），默认引用最后一个表单；
    
    这个需要通过 `<stl:form title="表单名称">`来指定对应的表单

2、表单提交未过滤<html、<script ,前台可提交任何形式的<html、<script ，后台都按照<html、<script 语法显示，严重影响网站安全；

    这个问题已修正，升级到最新版本即可。

3、表单数据浏览无法关闭，
网址/SiteFiles/Plugins/SS.Form/templates/list1/index.html?siteId=&formId=&apiUrl=%2Fapi，任何人知道siteID、formID，无需登录管理后台，均可打开浏览表单数据，存在数据泄露风险。
    
    这个问题已修复，必须输入formId的具体值才能获取表单数据。
