### ISSUE TITLE
tree 标签

### ISSUE THREAD

**Issue by Jason-mxy** [siteserver/cms#156]
<stl:tree channelName="首页" groupChannel="nav"></stl:tree> 
 设置栏目组，栏目组下的子栏目没有显示。

<stl:tree channelName="首页" groupChannel="nav" title="树状图"></stl:tree>
title属性没有起作用。

**Comment by starlying** [comment]
问题一已解决。

问题二：
title属性是设置根节点显示名称
<stl:tree channelName="首页" groupChannel="nav" title="树状图"></stl:tree>
设置栏目组后栏目树不显示根节点，所以设置无效。
