### ISSUE TITLE
 未将对象引用设置到对象的实例。

### ISSUE THREAD

**Issue by YellowTulipShow** [siteserver/cms#1605]
在 SiteServer.API.Controllers.Home.HomeController.GetContents(RequestImpl request)   在 SiteServer.API.Controllers.Home.HomeController.GetConfig()

**Comment by YellowTulipShow** [comment]
管理员账号 admin  用户账号admin 分别创建  当使用/home地址登录系统用户账号时抱错, 无法进入页面

**Comment by starlying** [comment]
我们测试是正常的，看看是不是哪里设置不一样导致的
