### ISSUE TITLE
6.7.6的表单功能无法使用 

### ISSUE THREAD

**Issue by nk915353337** [siteserver/cms#1610]
![default](https://user-images.githubusercontent.com/45165231/48697852-97853c00-ec20-11e8-97c3-dc3acd7b95d8.png)
![default](https://user-images.githubusercontent.com/45165231/48697877-aa980c00-ec20-11e8-9c95-7c35f3eab91d.png)
![default](https://user-images.githubusercontent.com/45165231/48697896-b7b4fb00-ec20-11e8-8b30-302fe078ef80.png)
![53x581gew9tturblz lpe](https://user-images.githubusercontent.com/45165231/48698120-40cc3200-ec21-11e8-9cb0-bf644f6bf094.png)
如图所示 
点表单管理，某一个表单，表单旁边的字段管理和选项设置都进不去
然后最后一张图是我做的一个投诉建议页面，没升级6.7.6前能显示投诉建议的提交表格，升级后就没了

请贵公司解决下，谢谢

**Comment by starlying** [comment]
打开浏览器console控制台，看看里面的报错信息是什么

**Comment by nk915353337** [comment]
![image](https://user-images.githubusercontent.com/45165231/48747012-c9dc7b00-ecac-11e8-9264-5b530d4282f1.png)
这个问题 看不大懂

**Comment by nk915353337** [comment]
![image](https://user-images.githubusercontent.com/45165231/48747173-5c7d1a00-ecad-11e8-9cf7-a602ef94e9a1.png)
![image](https://user-images.githubusercontent.com/45165231/48747185-66068200-ecad-11e8-9cc0-82afccec2d31.png)
这个问题 看不大懂

**Comment by nk915353337** [comment]
你们的“表单管理“用不了  插件什么的都装齐了

**Comment by nk915353337** [comment]
![image](https://user-images.githubusercontent.com/45165231/48748894-71f54280-ecb3-11e8-81e2-f36843bc3b42.png)
![image](https://user-images.githubusercontent.com/45165231/48748912-833e4f00-ecb3-11e8-87ad-78f8c66dce4a.png)
这是后台报错页面的控制台

**Comment by puzhengwu** [comment]
![image](https://user-images.githubusercontent.com/4401394/48929644-aa03bc00-ef25-11e8-86ff-0ef57c16fe1d.png)
这个BUG怎么解决

**Comment by puzhengwu** [comment]
我也出现这个问题了，怎样解决？

**Comment by puzhengwu** [comment]
翻到之前的issue，装了.net framework4.6.1,问题解决
