### ISSUE TITLE
下载的模板里面，SiteTemplateMetadata 里面的数据是怎么生成的呢？

### ISSUE THREAD

**Issue by xiaoyc** [siteserver/cms#1659]
Hi
 请问，下载的模板里面，SiteTemplateMetadata 里面的数据是怎么生成的呢？ 用什么工具么？

![image](https://user-images.githubusercontent.com/15319947/50138700-598c3e00-02da-11e9-8396-ee93b382bed5.png)

**Comment by starlying** [comment]
这是系统保存站点为站点模板时生成的

**Comment by xiaoyc** [comment]
感谢。
