### ISSUE TITLE
如何关闭站点？

### ISSUE THREAD

**Issue by jandykwan** [siteserver/cms#1720]
就是某站点，我目前暂时不想给公众看，先暂停。怎么操作呢？

**Comment by qianmengnet** [comment]
iis里面

**Comment by jandykwan** [comment]
我只是希望网站不对外开放，但网站功能还在。因为我内部其它系统还要利用里面的功能。

**Comment by xelnage** [comment]
静态生成页面的网站你就死了这条心吧 乖乖去web服务端关闭站点
