### ISSUE TITLE
4.1近期一直被注入木马，请问有解决方法吗？

### ISSUE THREAD

**Issue by g1293722517** [siteserver/cms#1733]
![qq 20190121094219_](https://user-images.githubusercontent.com/18181270/51448372-3df4d700-1d61-11e9-8a6e-7b76be2878c5.jpg)

大部分网站都被攻击，请问有没有解决方法？除了升级

**Comment by jiangbin4586** [comment]
\SiteFiles\SiteTemplates 这个目录下是可以清空的。当你保存完毕以后建议直接下载以后把这个目录清空，有需要再上传。 4.1 版本很老了，可以升级，不升级就需要加强服务器安全。后台登陆限制，等等吧
