### ISSUE TITLE
6.8.3，管理员登录提示验证码过期

### ISSUE THREAD

**Issue by lienmac** [siteserver/cms#1751]
rt，
换成这个6.8.3版本之后，管理员端登录一直提示【验证码已超时，请点击刷新验证码！】
服务器上安装和打开网页都是这样的提示，
请问如何修改
==============================
update
1. 如果用localhost可以登录，
2. 用域名就没办法登录，提示验证码超时，不管是在服务器还是在其他电脑上

**Comment by liuting525** [comment]
是的，我也出现了同样的情况，内网正常，外网验证码失效，我是从之前的版本升级过来的，但只升级成6.8.1，也不知道怎么才能升级到6.8.3

**Comment by jietoudeziyu** [comment]
更新一下服务器时间

**Comment by jietoudeziyu** [comment]
我也遇到了这个问题，找原因的时候瞄到服务器时间不对~

**Comment by liuting525** [comment]
是的，是服务器时间超过15分钟，验证码就会一直过期，只是没理解为什么内网不会，所以当时也没想到，非常感谢您的回答。

**Comment by lienmac** [comment]
我出现的问题是，同一台机器，用localhost和用域名方式访问，
用localhost可以登录
用域名就没办法登录，提示验证码超时

**Comment by liuting525** [comment]
对，我本地可以，用域名不行，原因就是服务器时间不对
