### ISSUE TITLE
后台STL语言参考有几处乱码。

### ISSUE THREAD

**Issue by Jason-mxy** [siteserver/cms#176]
![image](https://user-images.githubusercontent.com/10449120/34987009-aba63b44-faf4-11e7-8642-e4434b02f529.png)

![image](https://user-images.githubusercontent.com/10449120/34987013-afa537ea-faf4-11e7-846b-2c8163bf03cd.png)

![image](https://user-images.githubusercontent.com/10449120/34987019-b6135c92-faf4-11e7-9ec5-361e99338f20.png)

![image](https://user-images.githubusercontent.com/10449120/34987025-bd1959c4-faf4-11e7-9847-97d8744d3fc2.png)

**Comment by starlying** [comment]
已解决
