### ISSUE TITLE
初次安装时，管理员无法登录

### ISSUE THREAD

**Issue by greatfish** [siteserver/cms#1768]
根据官方安装向导安装，执行到第四步 运行SiteServer CMS安装程序时 需要管理员登录！！！
[https://docs.siteserver.cn/getting-started#/how-to-install-siteserver-cms](url)
版本号：6.8.3
问题1、不知道帐号密码（随便输也不行）
错误提示：值不能为 null。 参数名: connectionString

**Comment by shguanbin** [comment]
数据库管理员账号密码吧？

**Comment by greatfish** [comment]
> 数据库管理员账号密码吧？

不是 。 还没到设置数据库。
是在/siteserver/pageLogin.cshtml

**Comment by shguanbin** [comment]
你安装的url地址是多少？是不是访问错了地址

**Comment by shguanbin** [comment]
应该是***.com/SiteServer/Installer/index.aspx

**Comment by shguanbin** [comment]
方便的话截下图看看！

**Comment by greatfish** [comment]
> 应该是***.com/SiteServer/Installer/index.aspx

感谢！！！
官网的 
4、运行SiteServer CMS安装程序
打开浏览器（强烈建议Chrome或Firefox），因为刚才在第3步新建IIS站点时端口填写的是99，所以浏览器地址栏输入： http://localhost:99/siteserver/ 回车之后进入SiteServer CMS安装界面，如下图所示：

这有点误导人
