### ISSUE TITLE
SS.Filter内容筛选插件怎么使用

### ISSUE THREAD

**Issue by lizkvin** [siteserver/cms#1866]
如题，SS.Filter多重筛选怎么使用，没有说明文档，目前很需要这个功能～～求助～～～

**Comment by lizkvin** [comment]
因为没有说明文档，所以完全不知道怎么设置，后台就添加了一个分类设置，但也出不来结果，不知道应该怎么操作。。。 @starlying @17671877

**Comment by bizks** [comment]
是，没文档，想用用不来

**Comment by lizkvin** [comment]
@bizks 已经知道了，在筛选项的插件里面先设置下筛选项。然后去栏目设置里面，把筛选项的勾选，勾选上。这个时候进入到此栏目的内容管理里面，就可以设置筛选项了。就能出对应的结果了，可以试试。

**Comment by bizks** [comment]
调用有什么标签？

**Comment by LiuovWeb** [comment]
@lizkvin 怎么调用啊

**Comment by LiuovWeb** [comment]
@lizkvin 难道就只能在后台操作吗？
