### ISSUE TITLE
直接运行cms_dev,Installer完成后，点击进入后台，PageInitialization.aspx不会初始化系统

### ISSUE THREAD

**Issue by ceaserzhao** [siteserver/cms#19]
直接运行cms_dev,Installer完成后，点击进入后台，PageInitialization.aspx不会初始化系统,pagemain页面的左边都是空的，希望大师看看是否存在这个Bug 试了很多遍了

**Comment by starlying** [comment]
好的，我们查查

**Comment by ceaserzhao** [comment]
![qq 20170518110017](https://cloud.githubusercontent.com/assets/11839556/26184765/4e834254-3bb9-11e7-8c8b-73813d7e7e3f.png)
谢谢您及时的反馈，如图片所示，PageInitialization.aspx的试试 左边的菜单都没有，只出现右边的，也没有人让我添加站点的页面

**Comment by ceaserzhao** [comment]
已解决，和close中的问题9是一样的，在appSettings中加<add key="PageInspector:ServerCodeMappingSupport" value="Disabled" /> #9
