### ISSUE TITLE
6.10.1版本 在线模板无法访问

### ISSUE THREAD

**Issue by chopper7278** [siteserver/cms#1939]
6.10.1版本 在线模板无法访问
错误!   在线模板获取失败：页面地址http://templates.siteserver.cn无法访问！
文件我全局查找，siteserver_install\SiteServer\Settings\pageSiteAdd.aspx里面是http的  我改成https但是还是没有用，求解决方案！

**Comment by chopper7278** [comment]
实在没办法我就 创建空的站点。然后进入到管理页面以后，再去创建新的站点时候，选择在线模板居然就可以了。。。

**Comment by hjfzxc** [comment]
是的，我也遇到了这个问题。

**Comment by jiangbin4586** [comment]
siteserver_install\SiteServer\Settings\siteTemplateOnline.js 
不是应该修改这个js里面的地址吗？
