### ISSUE TITLE
最新开发版本：内容编辑器插入超链接和iframe保存后在链接前加/

### ISSUE THREAD

**Issue by gloomsky** [siteserver/cms#194]
在内容编辑器ueditor插入诸如http://www.baidu.com的超链接或iframe后，保存后在数据库中查看发现保存的字段http前有多加一个@，导致链接为@http://www.baidu.com格式，生成的链接为/http://www.baidu.com格式
![image](https://user-images.githubusercontent.com/5488401/35048263-733cdfb8-fbd7-11e7-8cd2-f6dc6b718908.png)
![image](https://user-images.githubusercontent.com/5488401/35048357-be94893e-fbd7-11e7-98bf-b769a10c4dac.png)

望解决为盼！

**Comment by gloomsky** [comment]
已自行解决。请关闭此问题。

**Comment by linghu86** [comment]
请问是如何解决此问题的？起码也说一下解决方案好不好
