### ISSUE TITLE
阿里云虚拟独享主机安装提示服务器错误

### ISSUE THREAD

**Issue by qnetadmin** [siteserver/cms#1981]
版本V6.11.1，把文件通过FTP上传到根目录后，尝试访问 安装向导.html文件，提示错误（如附件的），我看了前面有的网友出现这个问题是.net版本不够高，我这个也是.net4.0 请问是要升级.net吗还是选择低版本的siteserver？或者有什么其他解决方法。
![安装测试](https://user-images.githubusercontent.com/52565779/60712574-e54d7b00-9f49-11e9-8003-32998bc3369e.png)

**Comment by wangjiang8000** [comment]
你这个提示不是2.0的.net么？哪里显示是4.0的了？你好好的确认一下吧，新6版本以上是需.net 4.以上才可以的。

**Comment by qnetadmin** [comment]
我知道这个提示是2.0，但是我在主机后台看到的信息是这个  
支持语言： .NET1.1/2.0/3.5/4.0、ASP、HTML、WAP
那我是要阿里云的技术帮忙升级.net咯？

**Comment by wangjiang8000** [comment]
你建网站的时候有一个.net 版本的选择，通过iis配置的时候。你在那个地方看一下吧，如果是云虚拟主机的话就是买的时候就有自带的环境的。

**Comment by qnetadmin** [comment]
嗯嗯，我已经在阿里云的后台提交工单了，.net4 看能不能升级。

**Comment by nhren** [comment]
自己在云虚拟主要的管理面板那里选择.Net版本

**Comment by qnetadmin** [comment]
感谢你@nhren 真的可以自己选择.net版本，我选择了.net 4.0集成，立马就好了。就在主机管理，高级管理设置。
![选择net版本](https://user-images.githubusercontent.com/52565779/60714525-d072e680-9f4d-11e9-8c0c-0ee0c5733233.png)
