### ISSUE TITLE
漏洞 Unencrypted __VIEWSTATE parameter

### ISSUE THREAD

**Issue by ceaserzhao** [siteserver/cms#20]
如果webconfig加了配置 可是页面都无法生成了
![viewstate1](https://cloud.githubusercontent.com/assets/11839556/26185822/cc90bdec-3bbf-11e7-9213-af6c168e7c7a.png)
![viewstate](https://cloud.githubusercontent.com/assets/11839556/26185831/e325dcc2-3bbf-11e7-8409-867fc1c59b68.png)
![viewstate2](https://cloud.githubusercontent.com/assets/11839556/26185898/584eeea8-3bc0-11e7-927b-9fdfa0269e45.png)

**Comment by starlying** [comment]
web.config里面加了什么导致的？

**Comment by ceaserzhao** [comment]
图2是漏洞的解决方案 加了 <machineKey validation="AES"/>  这样页面就无法生成了

**Comment by starlying** [comment]
这个漏洞是误报，所有ASP.NET程序都会报这个漏洞，里面写的解决方案也是不对的
