### ISSUE TITLE
最新的release安装版无法安装

### ISSUE THREAD

**Issue by seamusic** [siteserver/cms#207]
https://github.com/siteserver/cms/releases/download/siteserver-dev-v5.0.153/siteserver_install.zip

刚试用了一下，按教程 http://cms.siteserver.cn/contents/131/426.html# 里提到的，设置好IIS站点后，
浏览http://域名/siteserver/installer/default.aspx 提示重定向过多，无法进行下一步安装。

**Comment by Jason-mxy** [comment]
测试安装没有问题；安装参考：http://docs.siteserver.cn/getting-started/install.html
