### ISSUE TITLE
栏目模板里为什么会引用 jquery-1.9.1.min.js ？

### ISSUE THREAD

**Issue by huima80** [siteserver/cms#2077]
我的栏目模板里并没有引用 jquery-1.9.1.min.js，但最后生成的页面里，在body下第一行有：
<script src="/sitefiles/assets/components/jquery-1.9.1.min.js" type="text/javascript"></script>

看了下模板代码，可能是模板的分页指令stl:pageItems 引入的，但这个版本太老，而且在 head 文件中已经全局引用了最新版的 jquery，导致页面中同时存在两个不同版本的jquery，导致后面的JS代码全部出错。

请确认并修正。

**Comment by jiangbin4586** [comment]
![image](https://user-images.githubusercontent.com/37280203/63820616-7b1aea80-c97c-11e9-840b-2a574dc8cadd.png)
去后台这个地方改一下，改成否就可以了。默认 选项是 是

**Comment by huima80** [comment]
> ![image](https://user-images.githubusercontent.com/37280203/63820616-7b1aea80-c97c-11e9-840b-2a574dc8cadd.png)
> 去后台这个地方改一下，改成否就可以了。默认 选项是 是

解决了，多谢！
