### ISSUE TITLE
v6.12升级后 后台登录成功后马上自动退出，所有账号如此

### ISSUE THREAD

**Issue by qqyule** [siteserver/cms#2091]
测试过多台电脑都是这样，现在根本无法登录上后台了

**Comment by jiangbin4586** [comment]
升级完毕，账号第一次登陆是直接闪退的。再次登陆就不会退出了啊。可能是因为更新了下面这两项导致受到了影响？
![image](https://user-images.githubusercontent.com/37280203/64137495-1f90a700-ce2b-11e9-9076-5c1e1c8f699c.png)

**Comment by qqyule** [comment]
可能由于升级不完全引起，覆盖新版SiteServer文件夹已解决
