### ISSUE TITLE
内容生成是否支持自定义路径

### ISSUE THREAD

**Issue by seamusic** [siteserver/cms#2094]
内容生成是否支持自定义路径？目前看到是没有的，后续是否有支持的计划？

**Comment by jiangbin4586** [comment]
支持啊，在URL自定义界面可以自定义啊

**Comment by seamusic** [comment]
看到了，在静态生成设置中有。一般其它cms都是在添加文章的时候设置的。

**Comment by seamusic** [comment]
不对哦，那个只是修改栏目的。我想问内容的。
url自定义界面在哪里呢？

**Comment by jiangbin4586** [comment]
![image](https://user-images.githubusercontent.com/37280203/64163754-6b1b7300-ce74-11e9-8fda-b318ff00edf6.png)
一样啊，都在这里啊。

**Comment by seamusic** [comment]
不好意思……您误会了，我想问的是，每一篇文章是否可以自定义生成路径……

**Comment by jiangbin4586** [comment]
单篇内容没法自定义，最少都要一个栏目里面才可以的。
