### ISSUE TITLE
源码无法运行呀 好多错误 

### ISSUE THREAD

**Issue by 331824047** [siteserver/cms#21]
是步骤不对吗
解决方案需要手动添加web站点 ，
然后运行web提示SiteServe.API  Global不存在
重新引用之后，又提示SiteServer.BackgroundPages下面好多文件不存在

**Comment by starlying** [comment]
可能是打开的方式不对，可以看看SiteServer CMS 5.0 源码入门：http://docs.siteserver.cn/development/214.html
