### ISSUE TITLE
辅助表管理——虚拟字段管理——页面乱码

### ISSUE THREAD

**Issue by mingjie888** [siteserver/cms#214]
辅助表管理——虚拟字段管理——页面乱码、真实字段出现在虚拟字段中了。

**Comment by mingjie888** [comment]
![image](https://user-images.githubusercontent.com/18482244/35211861-1f9beb5a-ff93-11e7-91a9-1cd8f845d082.png)

**Comment by starlying** [comment]
已解决

**Comment by dzlishen** [comment]
这个问题怎么解决，需要怎么更新呢。

**Comment by starlying** [comment]
4月1日会出升级包，后台升级即可
