### ISSUE TITLE
域名直接指向子文件夹，现在搭建好了之后 必须要在域名后面加入文件夹名称才能访问

### ISSUE THREAD

**Issue by chowchowstyle** [siteserver/cms#2150]
域名直接指向子文件夹，现在搭建好了之后 必须要在域名后面加入文件夹名称才能访问！比如 我想直接访问www.xxxx.com;但是现在必须得这样输入才能访问网站首页www.xxxx.com/子文件夹名称/。感谢！

**Comment by jiangbin4586** [comment]
iis 指向子文件夹，后台登陆以后也把子站绑定这个域名。然后一键生成。就可以了.

**Comment by chowchowstyle** [comment]
可以了 感谢了！

**Comment by zsinba** [comment]
为什么不在系统里做域名的路由呢？
