### ISSUE TITLE
版本6.12安装SS.Gather采集插件后运行错误 Table 'cms5.0.ss_gather_rule' doesn't exist

### ISSUE THREAD

**Issue by lpy3654321** [siteserver/cms#2158]
版本6.12安装SS.Gather采集插件后运行错误 Table 'cms5.0.ss_gather_rule' doesn't exist。
重新下载安装包安装也是，删除重新、重新加载所有插件都是这样的错。

![image](https://user-images.githubusercontent.com/6957984/66265091-f35db100-e842-11e9-8667-f0558b3abbd3.png)

**Comment by jiangbin4586** [comment]
删除插件，然后去数据库对应的表也删除，然后重新安装试试呢

**Comment by lpy3654321** [comment]
> 删除插件，然后去数据库对应的表也删除，然后重新安装试试呢

我不知道有哪些表呀？

**Comment by jiangbin4586** [comment]
ss_gather 只要是这样开头的都是采集的表，删除，重新安装试试

**Comment by lpy3654321** [comment]
应该是环境没有设置好，我按着官网的说明重新设置所有后，可以使用了。
