### ISSUE TITLE
模板管理

### ISSUE THREAD

**Issue by Jason-mxy** [siteserver/cms#221]
模板管理中有乱码。
![image](https://user-images.githubusercontent.com/10449120/35434706-06ab2574-02c3-11e8-820c-6f79270f251b.png)

**Comment by Jason-mxy** [comment]
点击 1 再点击 2 ，模板为空。
![image](https://user-images.githubusercontent.com/10449120/35434827-7eafeb9a-02c3-11e8-8757-18d58c749f0c.png)

而且选项卡有遗漏。
![image](https://user-images.githubusercontent.com/10449120/35434865-9cce0f08-02c3-11e8-8154-871b8e40018a.png)

**Comment by Jason-mxy** [comment]
STL在线解析，模板类型选择乱码。
![image](https://user-images.githubusercontent.com/10449120/35435104-6a2c6c88-02c4-11e8-9ca9-3b50b1a22c09.png)

**Comment by starlying** [comment]
已解决
