### ISSUE TITLE
管理员管理

### ISSUE THREAD

**Issue by Jason-mxy** [siteserver/cms#223]
创建管理站点角色分配给一个账号，使用此账号登录后台没有我的用户菜单，无法退出后台。
![image](https://user-images.githubusercontent.com/10449120/35436599-022a55f4-02ca-11e8-84d2-38c983a1b95c.png)

![image](https://user-images.githubusercontent.com/10449120/35436749-9e2cd508-02ca-11e8-8ae8-714efbc16609.png)

**Comment by starlying** [comment]
已解决
