### ISSUE TITLE
PC站和手机站的数据怎么做的同步？

### ISSUE THREAD

**Issue by Xiaobaiaixiaobai** [siteserver/cms#2438]
你好，因为PC站和手机站的样式不一样，所有就创建了两个站点，现在发现再PC站点发布的文章，手机站点看不到？请问有什么办法解决吗？

**Comment by lcgtpr** [comment]
你解决这个问题了吗？

**Comment by Xiaobaiaixiaobai** [comment]
没有，准备研究代码，看能自己解决不。
________________________________
发件人: lcgtpr <notifications@github.com>
发送时间: 2020年5月28日 7:23
收件人: siteserver/cms <cms@noreply.github.com>
抄送: Xiaobaiaixiaobai <panzhuo123.0@outlook.com>; State change <state_change@noreply.github.com>
主题: Re: [siteserver/cms] PC站和手机站的数据怎么做的同步？ (#2438)


你解决这个问题了吗？

―
