### ISSUE TITLE
stl:count统计内容数会包含草稿和待审核内容

### ISSUE THREAD

**Issue by superyuri** [siteserver/cms#244]
如题：当用stl:count统计内容数的时候，比如

<stl:count type="Contents"></stl:Count>

计算的时候会包含"草稿"和“待审核”类型的内容。

建议可以通过附加属性的方式过滤掉"草稿"和“待审核”的内容

**Comment by starlying** [comment]
好的，我们会尽快修正

**Comment by starlying** [comment]
已解决
