### ISSUE TITLE
SiteServer目录是什么？为什么是编译过的呢？代码也没有注释。

### ISSUE THREAD

**Issue by 16it** [siteserver/cms#25]
SiteServer目录是什么？为什么是编译过的呢？代码也没有注释。希望有个合理的解释，谢谢！

**Comment by 16it** [comment]
抱歉，误会了，该目录的后台代码在项目SiteServer.BackgroundPages里面，既然都这么分了，建议直接改为MVC模式。不过注释问题确实有些不人道。

**Comment by starlying** [comment]
对，我们会逐步把代码文档完善起来
