### ISSUE TITLE
用户中心用户无法投稿

### ISSUE THREAD

**Issue by Jason-mxy** [siteserver/cms#251]
用户投稿设置了关联管理员，此管理员也有发文章权限，但是前台用户无法投稿,看不到投稿站点和投稿栏目。

![image](https://user-images.githubusercontent.com/10449120/36768640-2abbec10-1c7b-11e8-948c-ae30885a16e0.png)

![image](https://user-images.githubusercontent.com/10449120/36768218-04dd5c4c-1c79-11e8-93cd-70b065d2a3fc.png)

**Comment by starlying** [comment]
已解决
