### ISSUE TITLE
fileurl附件怎么设置才不下载（PDF文件）或者怎么获得真实链接？

### ISSUE THREAD

**Issue by tdk84e** [siteserver/cms#2553]
通过`<stl:content type="fileUrl"><stl:content type="Title" wordNum="50"></stl:content></stl:content>`获取到的附件地址为`pi/sys/stl/actions/download?siteId=1......`。附件全部为PDF文件，怎么才能浏览器直接打开？？

直接在浏览器输入`https://www.域名.com/upload/files/2020/8/75090046baa4e709.pdf`是可以打开的，通过附件链接就弹出下载

**Comment by tdk84e** [comment]
找到办法了{stl:content type=fileurl}

**Comment by cuikangjiejava** [comment]
如果是多个附件怎么办？
