### ISSUE TITLE
表单插件7.0在WIN7-IIS环境下，模板预览为空，不能使用自己新建的表单

### ISSUE THREAD

**Issue by ttpage** [siteserver/cms#2662]
表单插件7.0在WIN7-IIS环境下，模板预览为空，不能使用自己新建的表单

**Comment by ajhlp** [comment]
看下浏览器console， 如果是util.js 报 ACCESS_TOKEN_NAME undefined之类的，需要自己重新建一个表单模板，在最后面追加一个js就可以了

**Comment by ttpage** [comment]
好的，谢谢 ajhlp
