### ISSUE TITLE
siteserver只能通过localhost本地访问，无法通过ip地址访问，请问如何解决？

### ISSUE THREAD

**Issue by sunstudio** [siteserver/cms#2685]
使用http://localhost:5000可以本地访问，但是通过ip地址例如http://192.168.1.102:500就不能访问，请问我哪里设置不正确？
还有，如何修改端口号5000？
谢谢

**Comment by jiangbin4586** [comment]
在 （Nginx、Apache、IIS、Windows 服务）中运行 应该可以使用IP 的，我本地是iis 运行的，ip和端口都是通过iis里面配置的。
