### ISSUE TITLE
栏目页的栏目Id 如何设置为1？

### ISSUE THREAD

**Issue by lx4556332** [siteserver/cms#2686]
迁移数据，最新框架生成的Id 是2，修改数据库为1，保存、查看会报错。

**Comment by starlying** [comment]
直接修改数据库后到后台系统缓存界面中点击清空缓存再试试

**Comment by lx4556332** [comment]
{"message":"Object reference not set to an instance of an object.","addDate":"2020-10-27 09:05:01"}  直接修改数据库 清空缓存 在保存会报错。

**Comment by wenner** [comment]
> {"message":"Object reference not set to an instance of an object.","addDate":"2020-10-27 09:05:01"} 直接修改数据库 清空缓存 在保存会报错。

请问后面解决了么,怎么解决的?
我现在新建的 首页栏目ID是1 , 然后我想导入之前的, 只要已修改成其他 , 就报你上面的错误,不知道如何修改
