### ISSUE TITLE
7.0版本stl属性不工作

### ISSUE THREAD

**Issue by zch622** [siteserver/cms#2758]
运行环境：docker CE 19.03.13，serversitecms7.0.4
stl:channels topLevel
stl:channels 不能直接筛选二级栏目
stl:contents groupContent

**Comment by starlying** [comment]
应该没问题才对，我们核对一下

**Comment by zch622** [comment]
选择二级或更多级别的栏目，需要设置isTotal为true，之前没有添加这个属性
