### ISSUE TITLE
添加模板时报空引用错误

### ISSUE THREAD

**Issue by wxjv99** [siteserver/cms#2787]
### 环境信息
Ubuntu 20.04 / Docker / Net Core 3.1.9 / SS CMS 7.0.6

### 运行截图
![微信截图_20201125170242](https://user-images.githubusercontent.com/48554906/100205993-c1287a80-2f40-11eb-9ff4-f3651cd83b69.png)

### 日志信息
![微信截图_20201125170613](https://user-images.githubusercontent.com/48554906/100206094-def5df80-2f40-11eb-89d3-00eaefbee512.png)

### 
**本地调试无法复现，发生错误时 主站 模板数量为11个，从站 模板数7**
**手动添加模板文件和template表中记录后，手动添加的模板可以正常编辑和使用，从系统添加仍然报错**

**Comment by starlying** [comment]
测试没重现这个问题，我们接着查查

**Comment by wxjv99** [comment]
> 测试没重现这个问题，我们接着查查

很早之前遇到的了，不能稳定复现。先不管吧，遇到的概率不大，而且多半和特定的数/配置据有关。
