### ISSUE TITLE
字段设置出现样式错乱

### ISSUE THREAD

**Issue by sourcehome** [siteserver/cms#2857]
![截图20201220132821](https://user-images.githubusercontent.com/54975575/102705903-83acd800-42c7-11eb-99db-b7023c02827a.jpg)

如图，编辑字段时，提交类型选择单选项、多选项、单选下拉、多选下拉，设置选项为详细设置时，点击新增会出现样式错乱。

**Comment by sourcehome** [comment]
其次，字段设置列表页table上的 筛选 一行文字偏左，与下面table不对齐，应往右移10个像素，其他类似布局也一样。

**Comment by starlying** [comment]
估计是电脑分辨率导致的，把浏览器缩小一点应该就显示正常了
