### ISSUE TITLE
导入站点模板zip格式判断有误

### ISSUE THREAD

**Issue by sourcehome** [siteserver/cms#2859]
`file.type === 'application/x-zip-compressed';`

debug 后 发现为 application/zip

**Comment by sscmscom** [comment]
我们没看到对应的代码，具体代码是哪个文件？

**Comment by sourcehome** [comment]
> 我们没看到对应的代码，具体代码是哪个文件？

/wwwroot/sitefiles/assets/js/admin/settings/sitesTemplates.js -〉 uploadBefore 方法

**Comment by sscmscom** [comment]
收到，我们查查

**Comment by sscmscom** [comment]
已修复
