### ISSUE TITLE
模板上传问题

### ISSUE THREAD

**Issue by CharlesZHENG** [siteserver/cms#2879]
1. 环境：
- 12月25日从dockerhub上拉取的镜像。
- SSCMS 7.0.8
- 采用的MySQL
2. 问题描述：
官网下载的模板，用“好压”对模板解压，没有任何文件变动，用好压重新压缩为zip，上传，基于上传的模板创建站点，没有生成过程，生成的站点是空的。下载的模板原封不动上传正常。

**Comment by jiangbin4586** [comment]
你的级别对吗？文件夹T_xxx你要进去这个文件夹里面再压缩出来的，上传才可以把。如果是你是T_xxx右键文件夹直接压缩的话，压缩包解压会多出来一级T_xxx的，这样会导致后台不识别。

**Comment by CharlesZHENG** [comment]
666，真相了，厉害，是级别的问题。谢谢，谢谢。
