### ISSUE TITLE
6.x 版本数据能成功升级 7.0.9 ，后台无法登录。

### ISSUE THREAD

**Issue by xelnage** [siteserver/cms#2885]
![image](https://user-images.githubusercontent.com/5657596/103187512-829b2c80-48ff-11eb-996c-473b0a706c9f.png)

错误信息
{"message":"列名 'ExtendValues' 无效。\r\n列名 'CreatedDate' 无效。","addDate":"2020-12-28 11:25:09"}

**Comment by sscmscom** [comment]
运行一下/ss-admin/syncDatabase/试试

**Comment by xelnage** [comment]
> 运行一下/ss-admin/syncDatabase/试试

成功
