### ISSUE TITLE
新建Entity字段数量超过50，更新数据库会报错

### ISSUE THREAD

**Issue by sourcehome** [siteserver/cms#2890]
Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

建议可以自定义varchar长度，而非统一500

**Comment by sscmscom** [comment]
可以自定义，通过Length属性：

`[DataColumn(Length = 2000)]`

或者把类型设置为Text:

`[DataColumn(Text = true)]`

**Comment by sourcehome** [comment]
已解决
