### ISSUE TITLE
访问站点和预览站点显示的内容不一致

### ISSUE THREAD

**Issue by guodongme123** [siteserver/cms#2907]
预览站点的内容是对的，访问站点显示未修改的内容

**Comment by jiangbin4586** [comment]
预览站点的内容是动态的实时的。
访问站点显示的纯静态的内容，需要生成页面。

**Comment by guodongme123** [comment]
> 预览站点的内容是动态的实时的。
> 访问站点显示的纯静态的内容，需要生成页面。
生成页面之后，访问站点也是错的。。。

**Comment by guodongme123** [comment]
solved
