### ISSUE TITLE
siteserver V7.0.0如何实现对指定栏目下的内容的标题进行关键字搜索

### ISSUE THREAD

**Issue by zyq664975** [siteserver/cms#3016]
尝试过以下方法均达不到效果：
1.  <stl:pageContents channelIndex="膜法之路" pageNum="20" scope="descendant" where="title like %{Request.word}%">{Content.Title}</stl:pageContents>，有where属性但文档没有说怎么传，传字符串还是Boolean
2.   <stl:pageContents channelIndex="膜法之路" pageNum="20" scope="descendant"><stl:query type="WhereLike" column="title" value="%{Request.word}%"></stl:query>{Content.Title}</stl:pageContents>,会把内容列表显示出来，query标签不齐作用
3. <stl:search word=“{Request.word}” isDefaultDisplay="false">{Content.Title}</stl:search>,这样也不行，返回的是”系统正在搜索中，请稍后...“

**Comment by zyq664975** [comment]
siteserver版本为7.0.0

**Comment by jiangbin4586** [comment]
<stl:query>这个标签支持的版本是 7.0.10 以上。
where 就是sql 语句里面的where
建议您做好备份，先升级到最新版本7.0.10版本。
其实你3个搜索都方向错误了。

1.要先创建  <form> 标签设置好相关属性，这里也可以直接加搜索条件。比如限定那个栏目ID
2.创建单页模板 使用默认的 <stl:search>就可以了。


参考 [https://tieba.baidu.com/p/6859570322](url)

**Comment by zyq664975** [comment]
感谢解答，升级后已经解决。
