### ISSUE TITLE
参照“在 Windows 中运行 SS CMS”安装完成，进入后台管理为空白页

### ISSUE THREAD

**Issue by cnlstar** [siteserver/cms#3023]
如题，环境为：windows sever12 +iis ，腾讯云服务器。

进入网址../home时，有登录注册页面，注册成功，但用新注册的帐户进入时，提示成功，但一停在“页面加载中”提示。
查sqlite数据库文件中，有增加的用户帐号。
初次使用SS CMS，请问一下如何处理？
谢谢！

**Comment by cnlstar** [comment]
追加：
昨晚在官网（https://sscms.com/）注册帐号时，也是类似现象，注册成功后，登录时也是卡在“页面加载中”提示无反应。

**Comment by sscmscom** [comment]
会不会是浏览器导致的，换成chrome浏览器试试

**Comment by cnlstar** [comment]
你好，用过也是一样。今天你们登录官网可以了，不在卡住不动了。
现在试着用四台电脑，用不同的浏览器访问这个测试网址：&nbsp;
http://49.234.234.208/home/&nbsp; &nbsp;&nbsp;
用户名：111&nbsp;&nbsp;
密码： `1q`1q
四台机器都是一样的，停在：页面加载中&nbsp;&nbsp;








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "siteserver/cms"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月4日(星期四) 下午4:14
收件人:&nbsp;"siteserver/cms"<cms@noreply.github.com&gt;;
抄送:&nbsp;"ls"<zuuz@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [siteserver/cms] 参照“在 Windows 中运行 SS CMS”安装完成，进入后台管理为空白页 (#3023)





 
会不会是浏览器导致的，换成chrome浏览器试试
