### ISSUE TITLE
Server Error in Application 'hoansi' 附近有语法错误。以 'AID6RAAAoEE7aQk 64aSvYJSCj2Y5UO9MuPEPNyURb14QnC9qzTyu0aSEL4ap/y8NwxEvdjOwr2yxzk9AwoePJACrjtFeVO9qfrjPNoRtT2R48M92kQzPQCqEz086qG8' 开头的 标识符 太长。最大长度为 128。以 'AID6RAAAoEHkma088akPPZsqmz0dyOK9mXNZvGUcXr1JOii 2fEHPWIqYL0nQqu9gjOSvVEFmb1H8

### ISSUE THREAD

**Issue by mahui-cn** [siteserver/cms#3055]
审核内容时出错，可能是往自定义字段里写入时出错，什么原因？

   在 System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)   在 System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)   在 System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)   在 System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean

**Comment by sscmscom** [comment]
是不是数据库增加了真实内容字段导致的，如果是的话把字段的长度修改一下，看报错是最大长度为 128不够用

**Comment by mahui-cn** [comment]
后来发现是因为迁徙数据库后，新建的表中的主键的自动增长属性丢失了，导致insert插入数据时报错。重新设置自动增长属性就好了。
