### ISSUE TITLE
{"message":"Unknown column 'TemplateId' in 'field list'","addDate":"2021-04-25 09:30:21"}

### ISSUE THREAD

**Issue by DonalLiu** [siteserver/cms#3075]
{"message":"Unknown column 'TemplateId' in 'field list'","addDate":"2021-04-25 09:30:21"}

**Comment by sscmscom** [comment]
具体是什么操作出现这个报错的？

**Comment by DonalLiu** [comment]
本地数据同步到服务器上之后，只要是对内容的操作就都提示这个错误
