### ISSUE TITLE
部署在iis站点的应用程序下有问题

### ISSUE THREAD

**Issue by Rendtime** [siteserver/cms#318]
问题:
1、后台管理无法点开左边手风琴样式的菜单，原因：SignalR路径错误，这个修改一下就可以了
2、用户中心打不开。。。

**Comment by starlying** [comment]
系统是不是部署在IIS站点下的应用程序里面？

**Comment by starlying** [comment]
哦，标题写了，我们会尽快修复，谢谢

**Comment by Rendtime** [comment]
是的，IIS站点下的应用程序里面。
由于端口问题，所以只好部署在应用程序里面
