### ISSUE TITLE
请问如何通过stl实现显示search结果的总数量

### ISSUE THREAD

**Issue by RyanHo97** [siteserver/cms#3243]
如题
<stl:count>
<stl:search>
能互相嵌套吗，如何绑定搜索结果

**Comment by RyanHo97** [comment]
自顶

**Comment by starlying** [comment]
可以在<stl:search>里面添加{PageItem.TotalNum}显示搜索结果总数量，参考：
https://sscms.com/docs/v7/stl/pageItem/
