### ISSUE TITLE
采集插件的问题

### ISSUE THREAD

**Issue by hqmlz** [siteserver/cms#3270]
增加采集规则之后，点击单页采集可以采集到一条数据。点开始采集却采集不到数据。
单页采集数据问题
![image](https://user-images.githubusercontent.com/67776643/142342308-2ada0e31-1135-43cd-a52b-51f541722f2a.png)
![image](https://user-images.githubusercontent.com/67776643/142342339-d4f2a15c-11d0-4df1-9470-f032dccf8423.png)
我选择的栏目是解决方案和产品下的子栏目情绪与生理测量，但是采集数据后给我放到了解决方案和产品下了。状态选择的是审核通过，采集数据生成后变成了待审核。
![image](https://user-images.githubusercontent.com/67776643/142342369-25e43e97-beeb-42cf-855d-3de745d5cd17.png)
这时候在去采集管理中编辑或者单页采集状态是待审核。
- 编辑页面
![image](https://user-images.githubusercontent.com/67776643/142342620-964e0f77-c0da-4089-b3b9-5fb3e39b3b46.png)
- 单页采集
![image](https://user-images.githubusercontent.com/67776643/142342596-45d1fe55-6025-4385-9c3d-946fbd8a8039.png)

**Comment by hqmlz** [comment]
还有一个问题，采集的附件图片文件是放到哪里了？

**Comment by starlying** [comment]
采集的附件图片文件是站点设置里面的上传图片设置规则是一致的
