### ISSUE TITLE
请教大佬子站搜索功能无效

### ISSUE THREAD

**Issue by powerren** [siteserver/cms#3298]
网站部署完毕后，我用官方自带的模板新建了一个子站，网站访问没有问题，但是使用网站首页上的搜索功能时，无论输入什么内容，都一直显示 “提示! 系统正在搜索中，请稍后...”

然后我尝试把这个子站转移到根目录，也就等于变成了主站了，搜索功能就正常了。

最近刚开始学习SSCMS，不知道子站的搜索是需要重新设置什么吗？

刚入门学习，还请各位大佬指点，谢谢！

**Comment by qianmengnet** [comment]
看看api是不是有不对的地方

**Comment by powerren** [comment]
> 看看api是不是有不对的地方

是的，后来发现是API设置的问题，谢谢！
