### ISSUE TITLE
命令行备份和恢复报错

### ISSUE THREAD

**Issue by summiry** [siteserver/cms#3369]
老版本（3.6.4）升级，备份数据库时报错：  The sscms.json file does not exist:
按照https://github.com/siteserver/cms/issues/2864 的方法新建了一个sscms.json文件后可以成功备份数据库，可是将老版本的数据恢复至新版本时又报错了： Database restore failed and the following table was not successfully restored: siteserver_DbCache

**Comment by doyou** [comment]
siteserver_DbCache这个表应该是缓存，不影响运行，我的还多几个表不成功，也没有问题。
主要是原网站内容、栏目能过来就行了。
