### ISSUE TITLE
杂志购物问题汇总

### ISSUE THREAD

**Issue by Jason-mxy** [siteserver/cms#337]
1、用户登录后不能退出；进入用户中心可以退出
2、杂志文章列表没有显示
3、我的订单页面空白
4、调查问卷数据导出出现404错误
4、平邮后台设置为0元，前台是快递的价格
5、订单结算页面的logo图片路径成了API路径，路径不正确
6、京东支付登录手机号无法修改，现在是固定的手机号
7、收货地址中应该有邮政编码这一项，平邮杂志都需要这个
8、付费文章，付完费后点击阅读还弹出付费窗口，无法进入到阅读页面；前台支付成功，后台状态是未支付。
9、导出投票结果出现404错误
10、投票输入验证码提示不正确
11、京东支付  支付完无法返回我们网站，一直停留在京东支付成功页面。在我的订单显示是未支付状态
12、投票交易记录导出的表示空的
13、每打开一个页面，都会弹出一个支付对话框闪一下

**Comment by starlying** [comment]
* [x] 1、用户登录后不能退出；进入用户中心可以退出
* [x] 2、杂志文章列表没有显示
3、我的订单页面空白
4、调查问卷数据导出出现404错误
4、平邮后台设置为0元，前台是快递的价格
5、订单结算页面的logo图片路径成了API路径，路径不正确
