### ISSUE TITLE
一定要更换数据库才能进行系统升级吗？

### ISSUE THREAD

**Issue by summiry** [siteserver/cms#3370]
3.6.4的版本想升级到最新版，按照官方文档使用命令行备份和升级了老版本数据结构，但发现最后无法将老版本的数据恢复至新版本中，说是要新建一个数据库才行。可是我用的云虚拟主机就只有一个默认的数据库，这样要怎么升级呢？

**Comment by qianmengnet** [comment]
在本地升级再导入到服务器

**Comment by summiry** [comment]
> 在本地升级再导入到服务器

可否讲具体一点，怎么导入服务器呢？我的网站用的不是云服务器是虚拟主机也可以导入吗？我按照官方的文档操作一直报错：ERROR  Database restore failed and the following table was not successfully restored: siteserver_DbCache

**Comment by qianmengnet** [comment]
我自己是新建了一个数据库，，远程连接过去，把老的备份，然后升级，还原到新数据库。  使用ssms远程管理就行。
