### ISSUE TITLE
后台突然进不去了

### ISSUE THREAD

**Issue by summiry** [siteserver/cms#3374]
请问这是什么原因啊
![image](https://user-images.githubusercontent.com/31307902/163968180-7444d156-96e8-4f27-9c0a-035724ce0dcd.png)

**Comment by leonedit** [comment]
检查你web.config第13行，看是不是配置文件或者.net环境出问题了

**Comment by summiry** [comment]
> 检查你web.config第13行，看是不是配置文件或者.net环境出问题了

第13行是这样子的，感觉没什么问题啊
![image](https://user-images.githubusercontent.com/31307902/164625661-b41556ef-60dd-440f-9d8e-2165e81483a6.png)
