### ISSUE TITLE
6.0.246 安装过程中对象名 'siteserver_Config' 无效

### ISSUE THREAD

**Issue by QingJ** [siteserver/cms#343]
![20180309112906](https://user-images.githubusercontent.com/19480748/37189121-a3f3a834-238d-11e8-8ce5-90c3f278bdaa.png)

**Comment by starlying** [comment]
选的是什么数据库？我们测试一下

**Comment by QingJ** [comment]
数据库用户权限不足，已经解决，谢谢！

**Comment by chenpoyang** [comment]
@QingJ 在哪弄, 我也遇到了, 弄没好SqlServer去弄MySql了, MySql说啥强制使用SSL啥的就又折腾回SqlServer, 好不容易弄好了SqlServer, 然而, 搜到了这个问题

**Comment by QingJ** [comment]
@chenpoyang 我当初是新建了一个数据库用户，但是忘了给权限了，用root登录赋予权限就行了
