### ISSUE TITLE
7.1.2 修改内容 API 有严重问题

### ISSUE THREAD

**Issue by oneeshine** [siteserver/cms#3447]
有如下内容：
![image](https://user-images.githubusercontent.com/31087083/184496951-556ae896-2b97-4846-a807-2fa461772263.png)
用/api/v1/contents/{siteId}/{channelId}/{id}   api获取内容如下：
![image](https://user-images.githubusercontent.com/31087083/184497008-5ee9d0b3-5757-4f3d-90bd-6e4726136671.png)
使用/api/v1/contents/{siteId}/{channelId}/{id}/actions/update  post以下数据
![image](https://user-images.githubusercontent.com/31087083/184497068-63376ea7-c613-4e2f-bfb5-b40d9ebe1384.png)
返回如下
![image](https://user-images.githubusercontent.com/31087083/184497092-43262607-7328-4b9b-b709-dc9d1eccdd80.png)
所有其他内容都变成了null，在后台中编辑器中所有内容显示为空，编辑后出错，并且无法删除
![image](https://user-images.githubusercontent.com/31087083/184497178-dd553887-1b40-490d-85cb-1f8a4ea6d9c4.png)
然而数据库中实际并没有变化
![image](https://user-images.githubusercontent.com/31087083/184497341-3f2a9406-b507-4cc3-856f-1e2d0e920740.png)

**Comment by oneeshine** [comment]
必须post完整的内容（也就是/api/v1/contents/{siteId}/{channelId}/{id}获取到的数据），才能正确修改，没有看源码，还是文档写错了？

**Comment by starlying** [comment]
收到，我们查一下

**Comment by mahui-cn** [comment]
> 收到，我们查一下

我升级到最新的 v7.3 ，在用API修改内容时，也发生和楼主一样的问题，请问这是BUG，还是文档描述不对？

**Comment by starlying** [comment]
是有bug，现已修复，重新下载更新一下即可。
文档也同步更新了。

**Comment by mahui-cn** [comment]
> 是有bug，现已修复，重新下载更新一下即可。 文档也同步更新了。

您好，
这个BUG修复了吗？

我看了文档 https://sscms.com/docs/v7/api/contents/update.html#%E8%AF%B7%E6%B1%82-uri
不知道是改了哪里？请求body中的所有参数似乎还是非必填项。接口没有变化吗？

另外，这个API应该是非常常用的，但这个帖子是2022.8就提出问题了，2年过去了，一直没有人发现这个问题吗？

**Comment by starlying** [comment]
所有参数均为非必填项，填写了那个参数，系统就会更新对应的参数值。

**Comment by mahui-cn** [comment]
我之前是通过这个接口，修改自定义字段，就会出现这个帖子里说的情况。
现在这个API还支持修改自定义字段吗？

**Comment by mahui-cn** [comment]
> 所有参数均为非必填项，填写了那个参数，系统就会更新对应的参数值。

我之前是通过这个接口，修改自定义字段，就会出现这个帖子里说的情况。
现在这个API还支持修改自定义字段吗？

**Comment by starlying** [comment]
自定义字段应该是支持的，可以再测试一下

**Comment by mahui-cn** [comment]
> 到官网首页下载即是最新版本：https://sscms.com

今天更新了这个最新版本，确实自定义字段都可以update了。另外发现 update API也变更了。 感谢。
