### ISSUE TITLE
stl:if 对象引用未设置为对象的实例

### ISSUE THREAD

**Issue by blackWins** [siteserver/cms#3500]
<html>
<body>

进程管理器 | Microsoft-IIS/7.5
-- | --
SSCMS 版本 | SSCMS 7.1.3
最近升级时间 | 2022-09-08 6:15
数据库类型 | SqlServer

</body>
</html>

模板标签：
```
<stl:channels>
	<stl:if type="GroupChannel" op="Empty">
		<stl:yes> GroupChannel Is Empty </stl:yes>
		<stl:no> GroupChannel Is not Empty</stl:no>
	</stl:if>
</stl:channels>
```

错误：
  "`category`": "stl",
  "`message`": "Object reference not set to an instance of an object.",
  "`stackTrace`": "   at SSCMS.Core.StlParser.StlElement.StlIf.TestTypeValues(String testOperate, String testValue, List`1 actualValues) in D:\\a\\1\\s\\build-win-x64\\src\\SSCMS.Core\\StlParser\\StlElement\\StlIf.cs:line 571\r\n   at SSCMS.Core.StlParser.StlElement.StlIf.ParseAsync(IParseManager parseManager, String testType, String testOperate, String testValue, String attributeYes, String attributeNo, String onBeforeSend, String onSuccess, String onComplete, String onError) in D:\\a\\1\\s\\build-win-x64\\src\\SSCMS.Core\\StlParser\\StlElement\\StlIf.cs:line 361\r\n   at SSCMS.Core.StlParser.StlElement.StlIf.ParseAsync(IParseManager parseManager) in D:\\a\\1\\s\\build-win-x64\\src\\SSCMS.Core\\StlParser\\StlElement\\StlIf.cs:line 224\r\n   at SSCMS.Core.Services.ParseManager.ParseStlElementAsync(String stlElement, Int32 startIndex) in D:\\a\\1\\s\\build-win-x64\\src\\SSCMS.Core\\Services\\ParseManager.StlElementParser.cs:line 230"

**Comment by blackWins** [comment]
channel context:

```
{
	"channelName": "MyChannelName",
	"siteId": 38,
	"contentModelPluginId": "",
	"tableName": null,
	"parentId": 46,
	"parentsPath": [38, 46],
	"parentsCount": 2,
	"childrenCount": 0,
	"indexName": "",
	"groupNames": null,
	"taxis": 15,
	"addDate": "2022-11-02 14:12:24",
	"imageUrl": null,
	"content": null,
	"filePath": null,
	"channelFilePathRule": null,
	"contentFilePathRule": null,
	"linkUrl": null,
	"linkType": "None",
	"channelTemplateId": 13,
	"contentTemplateId": 17,
	"keywords": null,
	"description": null,
	"children": null,
	"isCreateChannelIfContentChanged": true,
	"createChannelIdsIfContentChanged": null,
	"listColumns": null,
	"isPreviewContentsExists": false,
	"defaultTaxisType": "OrderByTaxisDesc",
	"isAllContents": false,
	"id": 64,
	"guid": "8a66cbbe-ada6-47ec-8e94-1e6e64349620",
	"createdDate": "2022-11-02 14:12:24",
	"lastModifiedDate": "2022-11-02 14:12:24"
}
```

**Comment by blackWins** [comment]
@siteserverekun @starlying

**Comment by starlying** [comment]
收到，是系统BUG，我们会尽快修复

**Comment by blackWins** [comment]
问题是否已修复？如已修复本issue将关闭。

> 收到，是系统BUG，我们会尽快修复
