### ISSUE TITLE
微信公众号获取用户列表和素材报错

### ISSUE THREAD

**Issue by bcthink** [siteserver/cms#3534]
配置正确，已经可以正常获取自定义菜单配置了，但是点击用户管理和获取图文素材就会报错，错误如下：
{"message":"The format of value '' is invalid.","addDate":"2023-01-31 19:16:04"}

另外，官方是否有计划开发可视化模板编辑

**Comment by starlying** [comment]
暂时没有开发可视化模板编辑的计划。
微信公众号用户管理和获取图文素材问题可能是由于微信公众号接口变化导致的，我们查一下
