### ISSUE TITLE
表单管理  一个bug

### ISSUE THREAD

**Issue by hdsslxl** [siteserver/cms#357]
在内容管理列表页 点击  表单管理 进来好像显示不全  一些字段编辑功能没有 360和谷歌浏览器都是 这样

**Comment by starlying** [comment]
确认，我们会尽快修正

**Comment by hdsslxl** [comment]
审查元素 把表单管理 那个链接  单独拿出来 在新标签页打开 就好了  确实是宽屏的问题

**Comment by starlying** [comment]
已解决
