### ISSUE TITLE
栏目属性设置的BUG

### ISSUE THREAD

**Issue by xelnage** [siteserver/cms#3583]
栏目属性设置中，选定链接到指定栏目，无法保存选择的栏目
![image](https://user-images.githubusercontent.com/5657596/234518848-85fef67f-bc45-4012-bcd1-13ca947bf73f.png)

**Comment by starlying** [comment]
我们本地测试是可以的，看看是不是后台页面JS脚本缓存导致的，清一下浏览器缓存试试，或者更新一下CMS后台再测测
