### ISSUE TITLE
feat：虚拟字段能否通过contents api进行排序

### ISSUE THREAD

**Issue by RyanHo97** [siteserver/cms#3586]
自己创建的虚拟字段目前并不能实现排序，未来有可以支持api虚拟字段排序的方式吗？
![image](https://user-images.githubusercontent.com/49436413/236593271-af19125c-b8bd-4598-8812-9f54022d541e.png)

**Comment by starlying** [comment]
虚拟字段不支持排序，只有真实字段才支持。可以手动到数据库中增加字段，系统会识别。

**Comment by RyanHo97** [comment]
> 虚拟字段不支持排序，只有真实字段才支持。可以手动到数据库中增加字段，系统会识别。

非常感谢您的回复
