### ISSUE TITLE
加上日期相关内容就报错，页面无法正常显示

### ISSUE THREAD

**Issue by yb12306** [siteserver/cms#3595]
加上日期相关内容就报错，页面无法正常显示：<stl:value type="Date" formatString="yyyy-mm-dd" ></stl:value>
![image](https://github.com/siteserver/cms/assets/18110584/96f5d4ce-e063-4c01-83ce-ebcfc76240e9)

**Comment by yb12306** [comment]
![image](https://github.com/siteserver/cms/assets/18110584/b3ceca06-e10f-4493-b649-99d289709a8f)

**Comment by starlying** [comment]
我们测试正常

`<stl:value type="Date" formatString="yyyy-mm-dd"></stl:value>`

不支持formatString属性，去掉再生成试试

**Comment by yb12306** [comment]
我去掉formatString也还是一样，只要去掉<stl:value type="Date"></stl:value>这个标签，生成之后页面就正常显示
