### ISSUE TITLE
<stl:tree> 树状导航 在sscms7.2 <stl:tree>标签信息还是解析不出来

### ISSUE THREAD

**Issue by TryFlyW** [siteserver/cms#3623]
升级到7.2后stl:tree标签信息解析还是不显示，是什么原因？
<stl:tree channelIndex="在线文档" groupChannelNot="树状导航" title="在线文档" currentFormatString="{0}"></stl:tree>
![1686109225849](https://github.com/siteserver/cms/assets/89243641/a8ffa1ba-ec7a-4cee-a445-0053d1fdbd8c)
文档上是有这个标签的
![image](https://github.com/siteserver/cms/assets/89243641/a2639f32-b5ed-4799-8585-54fa9e754e66)

**Comment by starlying** [comment]
stl:tree使用的js代码有问题，7.2之后这个标签就已经废弃了，推荐用Element UI的tree控件结合STL栏目列表或内容列表标签实现相关功能：
https://element.eleme.cn/#/zh-CN/component/tree

**Comment by TryFlyW** [comment]
> stl:tree使用的js代码有问题，7.2之后这个标签就已经废弃了，推荐用Element UI的tree控件结合STL栏目列表或内容列表标签实现相关功能： https://element.eleme.cn/#/zh-CN/component/tree
