### ISSUE TITLE
7.2.1版本前后台分离部署，前台(202.3)连上了后台的MySQL(202.4)，但是访问接口依旧返回401的问题吗？

### ISSUE THREAD

**Issue by sr6783** [siteserver/cms#3642]
前台（202.3）：Web服务 + API服务，可运行动态程序，可以访问静态页面，不可登录。按照[https://github.com/siteserver/cms/issues/3618](https://github.com/siteserver/cms/issues/3618)文档删除wwwroot\sitefiles\assets\js

后台（202.4）：程序+数据库。保留所有文件。数据库已经暴露给指定IP，连接已经建立，同时防火墙放开指定IP连接本地3306端口。

下图是前后台分离部署后，前台连接后台数据库成功截图
![前后台分离部署前台连接后台数据库成功截图](https://github.com/siteserver/cms/assets/22876599/46502081-ae69-40be-8a48-c7d57a64077a)

在202.3执行dotnet SSCMS.Web.dll，访问前台的接口页面报错401截图
![前后台分离部署error访问接口401](https://github.com/siteserver/cms/assets/22876599/f1167a4c-5a83-4761-8952-b3e7d822a8e7)

下图是在202.4上配置的API秘钥和接口地址，排除秘钥API秘钥错误和接口地址没设置的问题
![前后台分离部署error秘钥设置](https://github.com/siteserver/cms/assets/22876599/ab0013f8-d8ab-4679-b351-b5ac98cb7855)
![前后台分离部署error站点访问地址设置](https://github.com/siteserver/cms/assets/22876599/b8b0a83d-c261-4c9c-a6a6-88e118d3d6f6)

**Comment by starlying** [comment]
有可能是后台修改了API KEY之后，前台由于已经独立出来了，缓存不会自动清除，所以找不到API KEY导致返回401未授权。

重启一下前台服务器再试试。
