### ISSUE TITLE
登录时密码到期后强制修改密码时，存在密码明文传输问题

### ISSUE THREAD

**Issue by fsea** [siteserver/cms#3645]
![image](https://github.com/siteserver/cms/assets/7764467/38a12ec0-9d6e-4dbb-b628-1602f8295887)
如上图，其中红框中的password值是明文，建议和登录一样，修改为加密后再传输

**Comment by starlying** [comment]
收到，我们会尽快修复

**Comment by fsea** [comment]
今天看到password字段已经StringUtils.Base64Decode(request.Password);编码了
但是base64只是编码，并没有加密，
建议还是要加密再传输，只base64编码还是会泄露

**Comment by starlying** [comment]
这个修改密码功能和登录还不太一样，没办法把密码加密再传输，因为后台需要接受原始密码并加密存储到数据库中，如果用md5加密后就没法获取原始密码了。
