### ISSUE TITLE
IE9 设置兼容无法保存，报405错误

### ISSUE THREAD

**Issue by netsmallhao** [siteserver/cms#3651]
![image](https://github.com/siteserver/cms/assets/8485984/95b18d1b-2b79-4501-af8e-4b819376c99d)

去掉

可以保存，不报错， 加上就无法保存， 我应该如何保存这个代码，或者有什么标签可以替代

**Comment by starlying** [comment]
我们测试正常，是不是服务器安装了安全狗之类的防护软件导致的？

**Comment by netsmallhao** [comment]
> 我们测试正常，是不是服务器安装了安全狗之类的防护软件导致的？

7.2.1 版本 

    加上这个就报错， 服务器并没有加什么防护软件， ubuntu 22 版本

**Comment by starlying** [comment]
嗯，重新测试了一遍，我们这边还是正常，还有个办法，可以直接到服务器修改文件/include/header.html，和在后台修改效果是一样的。
