### ISSUE TITLE
建议优化登录等处的图形验证码

### ISSUE THREAD

**Issue by fsea** [siteserver/cms#3666]
建议采用微软序列号字符模式，减少相似字符出现，避免不必要的麻烦
微软产品一般都一个25位的序列号，是用来区分每份微软产品的产品序列号。产品序列号由五组被“-”分隔开，由字母数字混合编制的字符串组成，每组字符串是由五个字符串组成。如：
36XJE-86JVF-MTY62-7Q97Q-6BWJ2
每个字符是取自于以下24个字母及数字之中的一个：
B C E F G H J K M P Q R T V W X Y 2 3 4 6 7 8 9
采用这24个字符的原因是为了避免混淆相似的字母和数字，如I 和1，O 和0等，减少产生不必要的麻烦。

**Comment by starlying** [comment]
收到，已按上文优化验证码功能，谢谢反馈
