### ISSUE TITLE
可自定义表单提交成功

### ISSUE THREAD

**Issue by theme800** [siteserver/cms#367]
![tim 20180316120431](https://user-images.githubusercontent.com/16145195/37503226-1ebd04d2-2912-11e8-8c19-27d737b03f92.png)
这个在哪来自定义？
![tim 20180316120451](https://user-images.githubusercontent.com/16145195/37503240-2b421710-2912-11e8-8fe1-47437e26d59c.png)
勾选其他以后，后面的空必须填写，这个现在没做好限制吗？我看还是可以提交的。

**Comment by starlying** [comment]
已采纳

**Comment by starlying** [comment]
已完善
