### ISSUE TITLE
素材库为什么不做站点隔离

### ISSUE THREAD

**Issue by xelnage** [siteserver/cms#3678]
多个站点下素材库上传默认也是在全部分类，而不是在站点自身的分类下，而且没有任何的上传记录日志可以查询来源，这样就造成的管理混乱。
素材应该有描述字段。
素材库多站点下应该有隔离措施，授权后才能共享。

**Comment by starlying** [comment]
这个功能已经开发出来了，可以升级到最新版本，然后在这里设置：
<img width="852" alt="微信截图_20230830072024" src="https://github.com/siteserver/cms/assets/4256611/d7196657-f837-44fc-b996-13458c6bfebf">

**Comment by xelnage** [comment]
> 这个功能已经开发出来了，可以升级到最新版本，然后在这里设置： <img alt="微信截图_20230830072024" width="852" src="https://user-images.githubusercontent.com/4256611/264181906-d7196657-f837-44fc-b996-13458c6bfebf.png">

1：内容编辑时上传的素材默认为全部分类
2：素材库跨站应该为单个站点设置开关，而不是全局开关，而且现在不管是不是打开也能查看管理所有站点素材

**Comment by starlying** [comment]
最新的系统禁用素材跨站后，应该不会再显示素材分类了。
如果站点自己可以设置，那容易绕过，站点管理员设置为跨站就可以访问其他站点的素材了，所以通过全局设置，站点管理员无法设置，就可以确保不会访问到其他站点素材。

**Comment by xelnage** [comment]
> 

那么就剩问题1，内容编辑时上传到素材库的素材去哪了？按现在隔离规则，默认上传到全部分类，自己上传的素材也看不到了。
![image](https://github.com/siteserver/cms/assets/5657596/61932465-668b-4660-aeb2-29123094e68b)

**Comment by starlying** [comment]
我们这测试正常，会不会系统不是最新版本导致的，从官网下载最新的更新一下试试呢

**Comment by xelnage** [comment]
> 我们这测试正常，会不会系统不是最新版本导致的，从官网下载最新的更新一下试试呢

早上刚拉的31号版本，除了图片库，其它类型都还会显示分类，内容编辑上传除了图片其它也还是默认传到全部分类。
![image](https://github.com/siteserver/cms/assets/5657596/6ea2294a-5eaa-4784-8c14-f12bcd63a754)

**Comment by starlying** [comment]
收到，我们会尽快完善
