### ISSUE TITLE
搜索标签中，如果指定了不存在的栏目id，会导致搜不出任何结果

### ISSUE THREAD

**Issue by fsea** [siteserver/cms#3682]
并且/api/stl/actions/search会报400错误，
<stl:search type="title,body" channelIds="不存在id" isHighlight="true">
经过排查应该是SSCMS.Core\Repositories\ContentRepository.Get.cs中的public async Task<Query> GetQueryByStlSearchAsync(IDatabaseManager databaseManager, bool isAllSites, string siteName, string siteDir, string siteIds, string channelIndex, string channelName, string channelIds, string type, string word, string dateAttribute, string dateFrom, string dateTo, string since, int siteId, List<string> excludeAttributes, NameValueCollection form)方法：
![image](https://github.com/siteserver/cms/assets/7764467/a7a9e2cb-4616-43d6-b4bc-c6d83528d568)
如果theChannel=null则下一行会报错

**Comment by starlying** [comment]
收到，我们修复一下，谢谢反馈

**Comment by starlying** [comment]
问题已修复，谢谢。
