### ISSUE TITLE
在使用search时pagecontents报错：列名 'TAXIS' 无效

### ISSUE THREAD

**Issue by wingyBaci** [siteserver/cms#369]

**Comment by starlying** [comment]
是那个版本的系统？

**Comment by Devas9** [comment]
6.0

**Comment by starlying** [comment]
好的，我们确认一下

**Comment by linrb** [comment]
6.1.3版本我用search标签，也同样遇到列名 'TAXIS' 无效。，找了几个模板看到都是用 <stl:searchOutput>配合stl:pageContents>和<stl:itemTemplate>实现，现在STL 语言中没有stl:searchOutput说明，请问现在的版本到底用那个做搜索功能？

**Comment by Devas9** [comment]
可以暂时先屏蔽这个错误，修改ETaxisType.cs，
223： 行左右，把原来错误的请求排序注释， 换成默认的日期排序。

  else if (taxisType == ETaxisType.OrderByTaxis)
            {
                retval = $"ORDER BY {nameof(IContentInfo.IsTop)} DESC, {nameof(IContentInfo.AddDate)} ASC, {nameof(IContentInfo.Id)} DESC";
                // retval = $"ORDER BY {nameof(IContentInfo.IsTop)} DESC, {nameof(IContentInfo.Taxis)} ASC, {nameof(IContentInfo.Id)} DESC";
            }
            else if (taxisType == ETaxisType.OrderByTaxisDesc)
            {
                retval = $"ORDER BY {nameof(IContentInfo.IsTop)} DESC, {nameof(IContentInfo.AddDate)} DESC, {nameof(IContentInfo.Id)} DESC";
                //retval = $"ORDER BY {nameof(IContentInfo.IsTop)} DESC, {nameof(IContentInfo.Taxis)} DESC, {nameof(IContentInfo.Id)} DESC";
            }

**Comment by starlying** [comment]
已解决

**Comment by lawbc** [comment]
请问那个版本解决的，6.1.3还是这样

**Comment by starlying** [comment]
升级到6.2以上版本均可

**Comment by lawbc** [comment]
谢谢，升级后已解决
