### ISSUE TITLE
系统如何设置取消缓存

### ISSUE THREAD

**Issue by lawbc** [siteserver/cms#3723]
有些数据是数据库同步过去的，但是页面并不会显示出来，需要手动重新启动应用才行或者刷新缓存，是否能设置不要缓存呢

**Comment by lawbc** [comment]
比如自己手动从数据库新增了数据，在cms后端页面看不到新增的数据，清空缓存也看不到，只能重启也行，能否有自动或者多少时间后刷新缓存呢

**Comment by starlying** [comment]
系统没有禁用缓存的设置，不过缓存都有过期时间，根据数据使用频率，过期时间也有所不同。

**Comment by lawbc** [comment]
比如：
1、某个栏目的内容数据库删除了，然后新增进去，那么多久缓存会刷新
2、某个栏目的扩展字段数据库更新了，那么多久缓存会刷新

**Comment by lawbc** [comment]
> 系统没有禁用缓存的设置，不过缓存都有过期时间，根据数据使用频率，过期时间也有所不同。

过期时间怎么看呢，现在我数据库新增了数据页面是看不到，等了很久都看不到

**Comment by lawbc** [comment]
另外点击页面的清空缓存也没有作用，如果这个有效果也能接受

**Comment by lawbc** [comment]
[ { "enablePerformanceCounters": false, "enableStatistics": false, "expirationMode": "None", "expirationTimeout": "00:00:00", "name": "07b9bbd3-48f3-45c3-ad9c-94589791a5a5", "key": "07b9bbd3-48f3-45c3-ad9c-94589791a5a5", "isBackplaneSource": false, "handleType": "CacheManager.MicrosoftCachingMemory.MemoryCacheHandle`1, CacheManager.Microsoft.Extensions.Caching.Memory, Version=1.2.0.0, Culture=neutral, PublicKeyToken=5b450b4fb65c4cdb" } ]

这个cacheHandleConfigurations是不是缓存永不过期

**Comment by starlying** [comment]
已修复，到官网下载最新版本升级一下即可。
现在手动修改数据库，再点击清空缓存应该能获取到最新的数据了。
