### ISSUE TITLE
新增表单内的数据出现401

### ISSUE THREAD

**Issue by felangsifor1** [siteserver/cms#3772]
普通管理员给予表单关联相应菜单权限后新增一条数据出现401跳转到登录页
![WeChat25945d7af8ceb7088f560b278a6db6ce](https://github.com/siteserver/cms/assets/49631435/8b2e553a-81c7-4009-9f2c-36645ed516e1)

**Comment by felangsifor1** [comment]
<img width="1296" alt="image" src="https://github.com/siteserver/cms/assets/49631435/02e98e44-8eb1-4e93-84c4-0b5a6dd75bed">
w'ba我把权限判断注释掉了，这儿报错了：The function evaluation requires all threads to run，但我感觉应该应该是我工程启动参数的问题

**Comment by starlying** [comment]
看看是不是修改代码带出来的问题，正常系统应该没这个问题
