### ISSUE TITLE
升级7.3后，点击内容管理报错

### ISSUE THREAD

**Issue by wanggouzi** [siteserver/cms#3774]
![image](https://github.com/siteserver/cms/assets/24426701/11090173-77a3-4041-9662-5b28e1b141b1)
如图

**Comment by wanggouzi** [comment]
点击内容搜索也报错
![image](https://github.com/siteserver/cms/assets/24426701/9bcc02c8-15d5-4787-8087-773f8202d9fe)

**Comment by wanggouzi** [comment]
请问是啥导致的

**Comment by wanggouzi** [comment]
突然又好了。。

**Comment by starlying** [comment]
应该是升级后浏览器还有缓存导致的，正常清空一下缓存就好了
