### ISSUE TITLE
更新后批量操作查询异常

### ISSUE THREAD

**Issue by felangsifor1** [siteserver/cms#3778]
![image](https://github.com/siteserver/cms/assets/49631435/0d91f533-5bf0-4889-8d8f-20568f3abd42)

**Comment by felangsifor1** [comment]
我在本地的另外一个环境测试，fileName后面是个..json，查询也没问题，有问题的这个的区别是我是复制的wwwroot和mysql到新的环境而不是用打包的wwwroot，本地的另一个环境则是使用的wwwroot

**Comment by starlying** [comment]
1、将产品升级到最新版
2、清除浏览器缓存
这两点都试一下，按说不会有问题

**Comment by felangsifor1** [comment]
都试过了，还是不行，有什么别的解决方法吗，我在新版本下创建的站点是没问题的，但现在是旧版本更新之后出现的问题

**Comment by starlying** [comment]
那有可能是文件没有升级，只升级了dll程序。
可以获取到新版本wwwroot下面的sitefiles、ss-admin、home这三个文件夹，覆盖到旧版本，然后清除浏览器缓存再试试

**Comment by felangsifor1** [comment]
按照您的操作处理之后查询正常了，我打包的时候wwwroot外挂到磁盘，所以没把本地的wwwroot打包上去，新环境则是完全使用的我本地的wwwroot
