### ISSUE TITLE
MSMQ安装后创建站点的时候不能选择指定辅助表 

### ISSUE THREAD

**Issue by dreamJune** [siteserver/cms#379]
不知道是否跟 #297 是同一个问题
  ##然后我通过修改后台数据（siteserver_table）
强制显示该辅助表后创建了新站点。。。
之后想删除该站点的时候，提示 
“对象名XXXX无效”

**Comment by starlying** [comment]
MSMQ是微软的消息队列吗？这个用到了SQLServer吗

**Comment by dreamJune** [comment]
不好意思，描述有误，愿意是
数据库选择了sqlserver，然后就无法正常显示辅助表，版本 233

**Comment by starlying** [comment]
sqlserver 是什么版本？我们测试一下

**Comment by dreamJune** [comment]
sqlserver 2012，不知道是不是部分初始化数据导入有误。
建议另外提供一份数据库结构，让开发者可以重置或者自己建库，更直接找到出错原因进行修复

**Comment by starlying** [comment]
建一个新的空数据库，选择这个数据库重新安装一下试试
数据库结构文档我们正在制作，应该不久能提供出来

**Comment by dreamJune** [comment]
居然又可以了，我之前用的也是一个空数据库。
迷之“在我这里正常”
