### ISSUE TITLE
进入管理界面为什是这样，如下图

### ISSUE THREAD

**Issue by coder-nox** [siteserver/cms#3799]
![3811722850973_ pic](https://github.com/user-attachments/assets/ebaabf09-637d-4111-84a6-39e7cce23a97)
输入http://localhost:8088/ss-admin/，回车返回空白页面，url变为http://localhost:8088/ss-admin/error/?uuid=114677d0-9fab-4e1d-9342-6b464b7895d1，每次输入http://localhost:8088/ss-admin/，返回url中的uuid是不同的

**Comment by starlying** [comment]
返回错误，要具体看看是什么原因导致的报错。

**Comment by coder-nox** [comment]
最终确定问题出在服务器缺这个ASPNETCoreModuleV2文件，大家可以参考[https://blog.csdn.net/qq_46051312/article/details/122648388](url)根据解决方案需要安装程序.Net Core对应的RunTime，（只需下载Hosting Bundle版本）
