### ISSUE TITLE
内容进入待审BUG

### ISSUE THREAD

**Issue by xelnage** [siteserver/cms#381]
版本：6.0.251
BUG现象：已保存内容点击编辑->预览，内容审核就会出现一条该内容的审核信息，点一次预览多一条信息，目前测试是无限添加审核信息，原栏目下的内容状态依然还是审核状态。

**Comment by starlying** [comment]
确认是bug，很快会修复

**Comment by starlying** [comment]
已解决，升级到6.0.252即可
