### ISSUE TITLE
上传附件时如果文件名含as字符，将会被删掉

### ISSUE THREAD

**Issue by zerofault-cn** [siteserver/cms#382]
例如准备上传的文件名叫yeast.pdf,上传时选择“采用原有文件名”，上传成功后变成了yet.pdf

**Comment by starlying** [comment]
好的，我们测试一下

**Comment by starlying** [comment]
是有这个问题，加到开发清单了

**Comment by zerofault-cn** [comment]
能否通过补丁更新，而不要整个系统升级，我现在版本是4.1.1603.我不想升级系统。

**Comment by starlying** [comment]
6.0以后才支持补丁更新，之前的没有办法
可以导出站点模板，重新安装新版本，然后导入站点模板
