### ISSUE TITLE
安装出错提示：错误!   Can't find file: 'model_content' (errno: 2)

### ISSUE THREAD

**Issue by shuomeng** [siteserver/cms#383]
安装版本：SITESERVER CMS 6.0.246
数据库：MYSQL5.5
系统：2012R2

请问怎么处理？是哪里错了？

**Comment by starlying** [comment]
查资料可能是MYSQL无法插入数据导致的：http://www.111cn.net/database/mysql/39527.htm
试试重新安装一个MYSQL，再安装CMS看行不行

**Comment by shuomeng** [comment]
重新安装mysql也装不了6.0以上的版本，装6.0以下的全部都正常可以的
