### ISSUE TITLE
ueditor超链接保存到数据库中加前缀@的Bug

### ISSUE THREAD

**Issue by linghu86** [siteserver/cms#384]
版本：6.0.233
例：
在编辑器中添加超链接
< a href="http://www.baidu.com" target="_blank">百度</a>

post到后台的数据是正常的，但后台应该是对超链接做了某些判断，在链接地址前加了@
符号，结果保存到数据库中：
< a href="@http://www.baidu.com" target="_blank">百度</a>

此时，在前端编辑该内容，取出来的值是：
< a href="/http://www.baidu.com" target="_blank">百度</a>

再次保存，数据库中的值：
< a href="@/http://www.baidu.com" target="_blank">百度</a>

在前端继续编辑该内容，取出来的值是：
< a href="//http://www.baidu.com" target="_blank">百度</a>

就是说，每次都会在原基础上往链接地址前加@符号？？是基于什么判断需要加@符号呢?

**Comment by starlying** [comment]
好的，我们马上查一下

**Comment by starlying** [comment]
我们测试正常啊，这个站点有什么特别吗，比如子站或者设置了独立API或其他？

**Comment by dreamJune** [comment]
我在233版本也遇到这个问题，在SiteServer.CMS.Core.ContentUtility的TextEditorContentEncode(***）中，输入一个外链地址， StringUtils.ReplaceHrefOrSrc(builder, url, "@");会把外链地址加一个@字符

**Comment by linghu86** [comment]
是主站，不是子站

**Comment by linghu86** [comment]
未设置独立的API

**Comment by starlying** [comment]
恩，我们查查代码

**Comment by starlying** [comment]
已解决，升级到6.0.253版本
需要修改web.config里面的IsNightlyUpdate为True，允许系统升级到最新开发版。
