### ISSUE TITLE
显示项的问题

### ISSUE THREAD

**Issue by xelnage** [siteserver/cms#396]
请问显示项能自定义吗，我需要内容的添加时间条目。
![default](https://user-images.githubusercontent.com/5657596/38015058-3ab3cc72-329d-11e8-9017-5f385cf3e062.png)

**Comment by starlying** [comment]
能自定义，在内容管理里面，上面一排按钮有一个显示项

**Comment by xelnage** [comment]
请看图，里面没有添加时间这个字段  AddDate。

**Comment by starlying** [comment]
还真是，是有问题，我们会在6.1给修正

**Comment by xelnage** [comment]
我觉的添加时间可以默认就放在页面中作为首选排序。

**Comment by starlying** [comment]
有道理

**Comment by starlying** [comment]
已修正
