### ISSUE TITLE
怎么解决在虚拟目录（或应用程序）下安装SiteServer找不到\signalr\hubs的问题？

### ISSUE THREAD

**Issue by hk8846** [siteserver/cms#415]
HTTP 错误 404.0 - Not Found
=========================================
模块	IIS Web Core
通知	MapRequestHandler
处理程序	StaticFile
错误代码	0x80070002
请求的 URL	http://www.projectgx.cn:80/signalr/hubs
物理路径	D:\wwwroot\popo1108\wwwroot\signalr\hubs （第二个wwwroot是我的应用web访问目录）
登录方法	匿名
登录用户	匿名

**Comment by starlying** [comment]
6.1版本已经解决

**Comment by hk8846** [comment]
这个问题是SiteServer部署在虚拟空间的一个Bug，修复办法后来我找到了，在根目录的web.config（非SiteServer里面的那个web.config）里面添加如下内容即可修复：
<system.webServer>
<validation validateIntegratedModeConfiguration="false" />
<modules runAllManagedModulesForAllRequests="true">
</modules>
</system.webServer>

**Comment by hk8846** [comment]
<validation validateIntegratedModeConfiguration="false" />
<modules runAllManagedModulesForAllRequests="true">
</modules>

**Comment by hk8846** [comment]
里面的那个内容为啥发不出来，显示空白！

**Comment by starlying** [comment]
用insert  code按钮试试

**Comment by hk8846** [comment]
解决方案：http://www.lxway.com/618929216.htm
