### ISSUE TITLE
最新版cms中stl:focusviewer 无法显示幻灯片

### ISSUE THREAD

**Issue by arhqs** [siteserver/cms#442]
原cms3.5版本的网站导入最新版cms6后，幻灯片无法显示

**Comment by starlying** [comment]
是有问题，我们会修复一下

**Comment by arhqs** [comment]
请问大概的修复周期是多长，如果一个多月的话考虑安装低版本，快的话等等，谢谢啦

**Comment by starlying** [comment]
正常要五月一号新版本出来才行，可以先用低版本，将来可以导出站点模板再安装新版本导入

**Comment by starlying** [comment]
经开发人员讨论，stl:focusviewer是由flash来播放的，目前主流浏览器已经放弃flash支持，比标签已废弃，需要用html加js实现轮播功能。
