### ISSUE TITLE
数据库mysql，栏目中文乱码

### ISSUE THREAD

**Issue by lienmac** [siteserver/cms#458]
1. 栏目中文名字全部为问号，数据库编码为utf-8
2. 点击生成页面，预览站点为空白页

siteserver系统版本：6.1.3
数据库版本：mysql 5.0
iis版本： 10.0

**Comment by starlying** [comment]
这个要设置一下mysql的编码，然后再安装系统，mysql默认是不支持中文的

**Comment by lienmac** [comment]
已经重新换过MySQL数据库的编码 为utf8_general_ci，包括里面的表也都是utf8_general_ci，并且重新安装系统
不过还是不行，是不是要修改什么配置文件？

**Comment by lienmac** [comment]
自行解决了
方法如下：

修改mysql配置文件/etc/my.ini。

[mysqld]
character-set-server=utf8 
[client]
default-character-set=utf8 
[mysql]
default-character-set=utf8

再重启下MySQL
