### ISSUE TITLE
翻页项首页末页无法解析

### ISSUE THREAD

**Issue by xelnage** [siteserver/cms#461]
版本：6.1.4-p

<stl:search>中的翻页项 "首页" "末页" 无法解析

<stl:pageItem type="FirstPage" text="首页"></stl:pageItem>
<stl:pageItem type="LastPage" text="末页"></stl:pageItem>
{PageItem.FirstPage}
{PageItem.LastPage}

输出为源码

生成的代码中也会附加上多余的xmlns标签
![image](https://user-images.githubusercontent.com/5657596/38548377-33de4ff2-3ce4-11e8-80bb-a6b75f18c546.png)

**Comment by starlying** [comment]
好的，我们确认一下

**Comment by xelnage** [comment]
以自己找到问题，已处理。关闭问题
