### ISSUE TITLE
虚拟主机执行安装SiteServer/installer/default.aspx出现白屏。

### ISSUE THREAD

**Issue by rzflybird** [siteserver/cms#467]
查看网页源码发现default.aspx只是执行了部分，如下，请问该如何解决：

    <!DOCTYPE html>
    <html>

    <head>
      <meta charset="utf-8">
      <title>SiteServer CMS 安装向导</title>
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="../assets/icons/favicon.png" rel="icon" type="image/png">
<link href="../assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="../assets/css/core.css" rel="stylesheet" type="text/css" />
<link href="../assets/css/components.css" rel="stylesheet" type="text/css" />
<link href="../assets/css/pages.css" rel="stylesheet" type="text/css" />
<link href="../assets/css/menu.css" rel="stylesheet" type="text/css" />
<link href="../assets/css/responsive.css" rel="stylesheet" type="text/css" />
<link href="../assets/css/ionicons.min.css" rel="stylesheet" type="text/css" />
<script src="../assets/jquery/jquery-1.9.1.min.js" type="text/javascript"></script>
<script src="../assets/sweetalert/sweetalert.min.js" type="text/javascript"></script>
<script src="../assets/layer/layer.min.js" type="text/javascript"></script>
<script src="../inc/script.js" type="text/javascript"></script>
<style>body{ padding: 20px 0; }</style>
      <link href="../assets/showLoading/css/showLoading.css?v=6.1.3" rel="stylesheet" />
	  <link href="password.css?v=6.1.3" rel="stylesheet" /> 
      <script type="text/javascript" src="../assets/showLoading/js/jquery.showLoading.js?v=6.1.3"></script>      
      <script type="text/javascript" src="password.js?v=6.1.3"></script>
    </head>
    <body>
      <form method="post" action="./default.aspx" id="ctl00" class="m-l-15 m-r-15">
<div class="aspNetHidden">
<input type="hidden" name="__EVENTTARGET" id="__EVENTTARGET" value="" />
<input type="hidden" name="__EVENTARGUMENT" id="__EVENTARGUMENT" value="" />
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="XWL7WuZgdZXEytmBUTAB58qNtYLTfs4P5vkd0p59vUvEVMFAe76KCcDq8fP5Hx6FR2Vxa0V6hd3JIm+Yh/DBgoGcwm4lDil0g4KdrsjKkQy+iBbRfIS70iwHRb3WazxA5m0VVyVo9TvUd7yQl6IXJD21yqVLhQi7JEwk7jymdjqV0TBAx7sAeJTZ9478btZ/1vCEQILbiCW8kVsyRNITy/5fydCxfqZnsnKAvWNnUwOBGVJaGHFcdU21W2lozY59r6NmLaw272lexxGzjDYbzLLnfEFPB0d2yhdSybdy2xaGf6vWwEFz+cjglpoYoF7q9QO8biGcAVUCFH3aNvHbcvP/jiJR3OkgLkFDpDNmi1hwxZxjqAzuVz0Iv52iryzCZPKwxowgtn9QMXKmY4WYHUUd7Lpk1CUOAVUOV7W0EMieJF5lvDrWqSdofsRA4q4hjXedro3m3WoFJKy0op+IfFy3hWDLu5BqR+6NSfUscZ71XzfmbNxfQW2jpt9gxWj9VXytoPpYJzrx+6gVpLz9/0xEvN7KfIe2Zh3i9AjdQm31iOpYX7C0GnHupbmVEs002nX8PzYRGIi9jY89FjPxGpJD/dZ0rFEO+bWmBZGt3C+8Wf+x0XQRU4kA626MrJeXZ4jgUq/3kGo9OVTPuiHEWhtgZPaJtapCTvE0IHy/5mqU1qJHXx3GbwfCfp1MDUg8VVb0x1CRotr36vIPaInjX0RH/tZg2XujiU/7QZD2abEfaVNT+RUDsoE8bvOY5snV" />
</div>

<script type="text/javascript">
//<![CDATA[
var theForm = document.forms['ctl00'];
if (!theForm) {
    theForm = document.ctl00;
}
function __doPostBack(eventTarget, eventArgument) {
    if (!theForm.onsubmit || (theForm.onsubmit() != false)) {
        theForm.__EVENTTARGET.value = eventTarget;
        theForm.__EVENTARGUMENT.value = eventArgument;
        theForm.submit();
    }
}
//]]>
</script>

<script src="

**Comment by starlying** [comment]
是什么浏览器？如果不是Chrome或Firefox建议更换一下试试

**Comment by rzflybird** [comment]
![1](https://user-images.githubusercontent.com/29532712/38659246-452ed290-3e5b-11e8-8ee6-297cceb425ee.png)
感觉还是和虚拟主机设置有关系，和浏览器关系不大，不知是不是这样，上图是谷歌浏览器的截图！

**Comment by starlying** [comment]
看截图没法确定问题，可以把虚拟主机的提供商和型号发给我们，我们测一测

**Comment by rzflybird** [comment]
已经搞定，供应商的问题，谢谢！
