### ISSUE TITLE
Mysql新建站点栏目乱码

### ISSUE THREAD

**Issue by zhangjian0111** [siteserver/cms#511]
![default](https://user-images.githubusercontent.com/24623/39390696-d65f13f8-4aca-11e8-9d17-c0ea30e8c198.png)
使用MySQL作为数据库时，通过在线模块新建站点时，栏目出现乱码。

**Comment by zhangjian0111** [comment]
在Web.config文件中ConnectionString指定charset=utf8;就可以了。

**Comment by starlying** [comment]
多谢提醒，我们会把编码增加到新版本里面
