### ISSUE TITLE
内容无法插入视频错误解决问题

### ISSUE THREAD

**Issue by ggm88** [siteserver/cms#52]
editor_config和ueditor.all.js经过修复后，再次发现添加视频后台成功前台不显示，后面奇葩的发现。视频：这个位置放视频地址进去前天奇迹般出现视频了！求解释和为什么？无法传图片上来！不知道时候能懂！

**Comment by ggm88** [comment]
就是这个位置必须填图片地址，然后前台才显示，注意我内容可是用的<stl:content type="Content"></stl:content>调用！

**Comment by starlying** [comment]
这个问题和UEDITOR有关系，我们正在查原因

**Comment by Jason-mxy** [comment]
已解决。
