### ISSUE TITLE
求助：后台自动升级到 siteserver-v6.1.27-beta后，管理后台无法进入

### ISSUE THREAD

**Issue by shuomeng** [siteserver/cms#520]
后台自动由  siteserver-v6.1.21-beta 升级到 siteserver-v6.1.27-beta后，后台无法进入

后台默认目录名siteserver被改为自己的目录名的情况下升级的。

升级完后，输入http://网址/后台目录/login.aspx   提示网址无法访问，重启服务器均不行。

**Comment by shuomeng** [comment]
直接下载6.2.4覆盖重新安装，原数据还在。已经正常可以使用。

**Comment by starlying** [comment]
好的，有问题再反馈给我们
