### ISSUE TITLE
Web.config 里面的加密字符串怎么解？

### ISSUE THREAD

**Issue by momoewang** [siteserver/cms#538]
用 siteserver.exe 升级旧版本时，发现 Web.config 里面的 ConnectionString 是加密的，备份无法正常运行。
怎么解决？

**Comment by starlying** [comment]
用 siteserver version 命令就可以看到解密和解密的字符串

**Comment by momoewang** [comment]
没有显示出来，怎么办？

E:\siteserver_install>siteserver.exe version
Welcome to SiteServer Cli Tool

SiteServer CLI Version: 6.2.4
Work Directory: E:\siteserver_install

SitServer CMS Version: 0.0.0.0
Database Type: SqlServer
Connection String Decode:
Connection String Encode:

**Comment by starlying** [comment]
要进入对应的文件夹里面

**Comment by momoewang** [comment]
是在对应的文件夹里面，数据库类型都解出来了。
    <add key="IsProtectData" value="True" />
    <add key="DatabaseType" value="9XtLPj6oytMAr6M9jZ....................
    <add key="ConnectionString" value="Zg3p37CSquM9cCIUZNz2C1NrkdqVA7e96................

**Comment by starlying** [comment]
看看web.config里面的SecretKey有没有值
如果还有问题，可以将web.config发送至support@siteserver.cn，我们测试一下

**Comment by momoewang** [comment]
我的 5.0 的 Web.config 确实没有 SecretKey.
已经发送至你邮箱，请测试一下。

**Comment by starlying** [comment]
好的

**Comment by starlying** [comment]
邮件已收到，在web.config里面添加：
<add key="SecretKey" value="vEnfkn16t8aeaZKG3a4Gl9UUlzf4vgqU9xwh8ZV5" />
再运行命令试试

**Comment by momoewang** [comment]
添加上就可以了，谢谢。
