### ISSUE TITLE
6.2.4 安装向导错误消息 列名 'IsCreatedInDB' 无效。

### ISSUE THREAD

**Issue by okcss** [siteserver/cms#541]
![Image of Yaktocat](https://raw.githubusercontent.com/okcss/tester/master/err.png)

服务器环境: Server2012
数据库: SQL2012 Express
IIS:8.5

**Comment by okcss** [comment]
额,好像解决了.
在这一步打开数据库的 siteserver_Table表 
把列 `IsCreatedInDb` 改为 `IsCreatedInDB`
把列 'IsChangedAfterCreatedInDb' 改为'IsChangedAfterCreatedInDB'
然后就通过了.

**Comment by okcss** [comment]
但是进入后台登陆时会提示 列名 `SettingsXML` 无效。
感觉 程序版本和数据库不匹配的吧.

**Comment by starlying** [comment]
嗯，我们查一下

**Comment by okcss** [comment]
找到问题解决办法了
安装SQLServer时,数据库排序规则选择了 `Chinese_CS_AI`  区分大小写
　　`_CI_AI   不区分大小写、不区分重音、不区分假名类型、不区分宽度 `   
　　`_CS_AI   区分大小写、不区分重音、   不区分假名类型、不区分宽度`
　　`常用的语言集为：Chinese_PRC_CI_AS`
执行SQL将数据库转换为大小写不敏感 问题解决
```sql
USE [master] 
GO 
ALTER DATABASE [DatabaseName] COLLATE Chinese_PRC_CI_AI 
GO
```
