### ISSUE TITLE
插件引用的资源的路径问题

### ISSUE THREAD

**Issue by masgcc** [siteserver/cms#559]
![qq 20180507113130](https://user-images.githubusercontent.com/39041525/39683844-586dc742-51ea-11e8-9d4b-837b26245db9.png)
比如主站点是：www.baidu.com 使用没问题 
但是子站点的：www.qq.com 使用就会出现问题
也就是资源的路径始终是 /SiteFiles/Plugins/SS.Login/assets/cleanslate.min.css 这样的

**Comment by starlying** [comment]
子站设置的独立访问域名吗？

**Comment by masgcc** [comment]
是的 采用了独立域名访问的

![qq 20180507120521](https://user-images.githubusercontent.com/39041525/39684525-0559c290-51ef-11e8-9b8d-e66bbc42a672.png)
![qq 20180507120535](https://user-images.githubusercontent.com/39041525/39684526-059f374e-51ef-11e8-8869-a75e5e79db37.png)

**Comment by starlying** [comment]
独立部署资源访问地址要设置绝对地址

**Comment by masgcc** [comment]
![qq 20180507163451](https://user-images.githubusercontent.com/39041525/39692826-9e51d576-5214-11e8-8318-8746f908f615.png)
无论做任何修改插件的资源引用地址均是以主站为根目录的方式 /SiteFiles/Plugins/SS.Login/assets/cleanslate.min.css

请问您说的绝对地址是否是主站的地址呢？例如主站是 www.abc.com 子站是 www.123.com
我现在环境是子站开启了独立访问 而插件安装是在主站的/SiteFiles/Plugins/目录下
子站的资源文件访问地址是否是www.abc.com呢？

**Comment by masgcc** [comment]
现在的问题就是 子站如何引用正确的插件的资源？

**Comment by starlying** [comment]
试试把API地址设置为绝对地址

**Comment by masgcc** [comment]
OK了 的确是需要修改API绝对路径
谢谢
