### ISSUE TITLE
BUG ｛Content.ContentID}  无效，栏目和内容列表属性 titleWordNum 无效，

### ISSUE THREAD

**Issue by yxmnshmily** [siteserver/cms#57]
BUG ｛Content.ContentID}  无效，栏目和内容列表属性 titleWordNum 无效，

**Comment by wang11268440** [comment]
{Content.ContentID}改成：{Content.ID}
栏目和内容列表属性 titleWordNum  已经不支持了，因为可以直接在嵌套标签里面设置，没有必要在外面设置了。
