### ISSUE TITLE
二级子栏目，子栏目页面不相似，创建栏目模板还是单页模板？

### ISSUE THREAD

**Issue by 33vonon** [siteserver/cms#587]
结构如下：
  公司简介
  - 公司介绍
  - 资质荣誉

导航跳转，我不知道该怎么创建页面。

创建栏目模板：公司简介
or
创建栏目模板：公司介绍、资质荣誉
or
创建单页模板：公司介绍、资质荣誉

**Comment by starlying** [comment]
应该是栏目模板，只要是栏目，不管是一级还是二级，都应该创建栏目模板
创建栏目模板之后要设置对应栏目，和模板匹配上

**Comment by 33vonon** [comment]
那是创建
栏目模板：公司简介
还是
栏目模板：公司介绍 和 资质荣誉
呢？
