### ISSUE TITLE
复制site文件夹后，然后再创建了一个新的site地址，新的没有访问成，旧的再访问也挂了。

### ISSUE THREAD

**Issue by 33vonon** [siteserver/cms#604]
复制site文件夹后，然后再创建了一个新的site地址，新的没有访问成，旧的再访问也挂了。

错误如下：
HTTP 错误 403.14 - Forbidden
Web 服务器被配置为不列出此目录的内容。

**Comment by 33vonon** [comment]
有默认的访问页，但是无法访问，求问怎么弄？

**Comment by starlying** [comment]
看看IIS站点有没有指向

**Comment by 33vonon** [comment]
emmm....是指运行后台管理，然后访问站点吗？我现在是没办法运行后台管理的。。就打不开呢。。
