### ISSUE TITLE
安装相册插件后提示加载此程序集将产生与其他实例不同的授予集。 (异常来自 HRESULT:0x80131401)

### ISSUE THREAD

**Issue by 33vonon** [siteserver/cms#617]
说明: 执行当前 Web 请求期间，出现未经处理的异常。请检查堆栈跟踪信息，以了解有关该错误以及代码中导致错误的出处的详细信息。 

异常详细信息: System.IO.FileLoadException: 加载此程序集将产生与其他实例不同的授予集。 (异常来自 HRESULT:0x80131401)

源错误: 
执行当前 Web 请求期间生成了未经处理的异常。可以使用下面的异常堆栈跟踪信息确定有关异常原因和发生位置的信息。

**Comment by starlying** [comment]
删除然后重新安装试试
或者手动删除SiteFiles/Plugins/SS.Photo文件夹，再进后台重载一下试试
