### ISSUE TITLE
生成时报空引用的异常

### ISSUE THREAD

**Issue by ListenChen** [siteserver/cms#624]
一键生成或是部分生成都出现很多这样的异常< 内容页生成失败  xxxxxx（错误：Object reference not set to an instance of an object.） >，请教下 出现该问题的原因是什么 或者 从哪儿可以看原因？谢谢！

另：提issue是不是不支持传图，传了没用。。提了之后是不是也不支持修改。。

**Comment by ListenChen** [comment]
因为浏览器原因 不支持传图 不支持修改， 更正下

**Comment by starlying** [comment]
进入系统错误日志，看看有没有详细报错信息
Chrome或者火狐都支持issue传图

**Comment by ListenChen** [comment]
![qq 20180517091439](https://user-images.githubusercontent.com/34906869/40151782-75ecc2f6-59b4-11e8-90a2-b4409b38d81f.png)
系统错误日志显示内容，就这两条重复显示，后台一些操作会导致这样的问题吗？有什么可以解决的方法？

**Comment by ListenChen** [comment]
@starlying

**Comment by starlying** [comment]
第一次遇到这个报错，系统使用的是哪个版本？

**Comment by ListenChen** [comment]
@starlying  系统使用的是 5.0 的版本，不过第二天之后<隔了一段时间>生成就不会显示红条，正常生成了，自动好了。。。最开始虽然显示红条生成失败，但实际上对应的内容也是生成成功的。。现在系统错误日志还剩一个“Server cannot set status after HTTP headers have been sent.”
