### ISSUE TITLE
在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误

### ISSUE THREAD

**Issue by russellyi** [siteserver/cms#633]
本地访问局域网SQL Server，不过IP变化了，就出现下面提示：
"在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)"

**Comment by russellyi** [comment]
已经冲洗配置。

**Comment by whatfee** [comment]
重新配置数据库要怎么配置？老哥，我也遇到了同样的问题，但配置了好像还是不行（安装官网那个来的）
