### ISSUE TITLE
6.2.14-b 升级数据库报错,如图

### ISSUE THREAD

**Issue by xelnage** [siteserver/cms#637]
![default](https://user-images.githubusercontent.com/5657596/40221452-18707e14-5aaf-11e8-865c-0ee7612e4ad2.png)

**Comment by starlying** [comment]
感觉是浏览器导致的，用的是什么浏览器？换用chrome试试

**Comment by xelnage** [comment]
所有浏览器返回错误相同, 图中的 api 地址返回错误消息.
"message": "The requested resource does not support http method 'GET'."

**Comment by starlying** [comment]
好的，我们查查

**Comment by starlying** [comment]
⊙∀⊙！
