### ISSUE TITLE
附件下载量排名是按照Taxis排序的，没有按下载量排名

### ISSUE THREAD

**Issue by Jason-mxy** [siteserver/cms#64]
附件下载量排名是按照Taxis排序的，没有按下载量排名；删除了带附件的内容，下载量排名中还会出现。

![image](https://user-images.githubusercontent.com/10449120/27526327-872190c0-5a77-11e7-9107-2eac002032e6.png)

![image](https://user-images.githubusercontent.com/10449120/27526291-5a93a16a-5a77-11e7-871b-f1a12668cfcd.png)

**Comment by starlying** [comment]
系统内容表中没有下载量字段，需要在统计量插件中实现
