### ISSUE TITLE
严重BUG，上级站点下属子站点不列出站点列表管理， 如何管理下属子站点？

### ISSUE THREAD

**Issue by yxmnshmily** [siteserver/cms#67]
严重BUG，站点下属子站点不列出站点列表， 如何管理下属子站点？
严重BUG，站点下属子站点不列出站点列表， 如何管理下属子站点？
严重BUG，站点下属子站点不列出站点列表， 如何管理下属子站点？

访问站点IDPublishmentSystemID=153 ？修改ID？

**Comment by lidong19860909** [comment]
确实有这个问题，但是siteserver官方的测试后台是可以查看所有站点的

**Comment by Jason-mxy** [comment]
已修复。
