### ISSUE TITLE
6.2.4版本是否已开放api?

### ISSUE THREAD

**Issue by thingpower** [siteserver/cms#680]
我安装了6.2.4版本,按照文档中心的说法可以通过http://example.com/api/v1/ping测试，但返回的信息是“No HTTP resource was found that matches the request URI 'http://localhost/api/v1/ping'.No type was found that matches the controller named 'v1'.”，请问是我后台配置有问题还是6.2.4没有提供api访问功能

**Comment by starlying** [comment]
API只在最新的开发版本中，还没有发布到正式版本，正式版本需要等到6月1日新版本发布。
如果希望提前体验，可以修改Web.config中的IsNightlyUpdate为true，今天后台后系统会提示升级到开发版。
