### ISSUE TITLE
Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='

### ISSUE THREAD

**Issue by russellyi** [siteserver/cms#833]
<stl:contents channelIndex="关于我们" groupContent="校长寄语"> <div class="container"> <div class="cuhksz-column-title"><stl:content type="Title"></stl:content></div> <p><stl:content type="Summary"></stl:content></p> <span style="font-size: 20px;">——<stl:content type="Author"></stl:content></span> <stl:a>了解更多</stl:a> <stl:a>校长办公室</stl:a> </div> </stl:contents> Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='

在 MySql.Data.MySqlClient.MySqlStream.ReadPacket() 在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId) 在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force) 在 MySql.Data.MySqlClient.MySqlDataReader.NextResult() 在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior) 在 System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior) 在 System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior) 在 System.Data.Common.DbDataAdapter.Fill(DataSet dataSet) 在 SiteServer.CMS.Data.DbHelper.ExecuteDataset(IDbCommand command) 在 SiteServer.CMS.Data.DbHelper.ExecuteDataset(IDbConnection connection, String commandText, IDataParameter[] commandParameters) 在 SiteServer.CMS.Data.DbHelper.ExecuteDataset(String connectionString, String commandText, IDataParameter[] commandParameters) 在 SiteServer.CMS.Provider.ContentDao.GetStlDataSourceByContentNumAndWhereString(String tableName, Int32 totalNum, String whereString, String orderByString) 在 SiteServer.CMS.Provider.ContentDao.GetStlDataSourceChecked(String tableName, List`1 channelIdList, Int32 startNum, Int32 totalNum, String orderByString, String whereString, LowerNameValueCollection others) 在 SiteServer.CMS.StlParser.Cache.Content.GetStlDataSourceChecked(List`1 channelIdList, String tableName, Int32 startNum, Int32 totalNum, String orderByString, String whereString, LowerNameValueCollection others) 在 SiteServer.CMS.StlParser.Utility.StlDataUtility.GetContentsDataSource(SiteInfo siteInfo, Int32 channelId, Int32 contentId, String groupContent, String groupContentNot, String tags, Boolean isImageExists, Boolean isImage, Boolean isVideoExists, Boolean isVideo, Boolean isFileExists, Boolean isFile, Boolean isRelatedContents, Int32 startNum, Int32 totalNum, String orderByString, Boolean isTopExists, Boolean isTop, Boolean isRecommendExists, Boolean isRecommend, Boolean isHotExists, Boolean isHot, Boolean isColorExists, Boolean isColor, String where, EScopeType scopeType, String groupChannel, String groupChannelNot, LowerNameValueCollection others) 在 SiteServer.CMS.StlParser.StlElement.StlContents.GetDataSource(PageInfo pageInfo, ContextInfo contextInfo, ListInfo listInfo) 在 SiteServer.CMS.StlParser.StlElement.StlContents.Parse(PageInfo pageInfo, ContextInfo contextInfo) 在 SiteServer.CMS.StlParser.Parsers.StlElementParser.ParseStlElement(String stlElement, PageInfo pageInfo, ContextInfo contextInfo)

2018-06-09 18:06:14

**Comment by starlying** [comment]
MySQL用的什么版本？

**Comment by russellyi** [comment]
mysql-5.5.60

**Comment by starlying** [comment]
没查出来问题，联系重新安装系统试试
