### ISSUE TITLE
 Data too long for column 'Summary' at row 1

### ISSUE THREAD

**Issue by russellyi** [siteserver/cms#834]
Data too long for column 'Summary' at row 1

在 MySql.Data.MySqlClient.MySqlStream.ReadPacket() 在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId) 在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force) 在 MySql.Data.MySqlClient.MySqlDataReader.NextResult() 在 MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior) 在 MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() 在 SiteServer.CMS.Data.DbHelper.ExecuteNonQuery(IDbCommand command) 在 SiteServer.CMS.Data.DbHelper.ExecuteNonQuery(IDbConnection connection, String commandText, IDataParameter[] commandParameters) 在 SiteServer.CMS.Data.DbHelper.ExecuteNonQuery(String connectionString, String commandText, IDataParameter[] commandParameters) 在 SiteServer.CMS.Provider.SiteLogDao.Insert(SiteLogInfo log) 在 SiteServer.CMS.Core.LogUtils.AddSiteLog(Int32 siteId, Int32 channelId, Int32 contentId, String adminName, String action, String summary)

2018-06-02 11:32:52

**Comment by starlying** [comment]
查代码没看出问题来，手动修改siteserver_SiteLog表的Summary字段，把长度改成255试试

**Comment by russellyi** [comment]
该字段已经是255了
