### ISSUE TITLE
SiteServer5.0表单提交

### ISSUE THREAD

**Issue by kolostef** [siteserver/cms#842]
前台用模板写成
 <stl:InputContents  pageNum="8" order="AddDate" inputName="在线问题征集"   isReply="true">              
               <li>
                 <stl:inputContent type="title" ></stl:inputContent>
                 <span><stl:inputContent type="AddDate" formatString="yyyy-MM-dd"></stl:inputContent></span>
 </li>           
    </stl:InputContents>

没有任何问题，想做翻页列表，stl:InputContents 然后改成pageinputContents标签,前台显示就会输出一堆字符乱码

**Comment by starlying** [comment]
看看模板里面加了utf8编码没有

**Comment by kolostef** [comment]
有加，用标签stl:InputContents就是正常显示 标题+时间
用了 stl:pageinputContents 页面生成前台显示,本该出现标题+时间的部分就会出现很长的字符
例如：e8lUF0slash0a6ssRGwr4ECVr4INVZzq0PGe9fJtAr5JQyknPNWJIfrmIau21xG4Djb5PZRP5LdlOMIyAmGbXGDy6mTdosmI6Gw5kmL4l4uaNSbgvInMpS1kkgl790add0T9BhlwT9nrt0slash0K92PhstrifHacMyc4uSKVfXw3yIuixfGMGWk9A17DSYoLZEWPWnEZ0slash04RYGNMT7h4kIsCC0slash0wp0AUOhp1YS5tB0mTUzOv0slash03nxbSYxKOgzHc2KPBXLxMhCHFihTW22xC7ACRrKEDLJrfMO4pI3Rsd4R5UfaFDT3jQBxeQlMzkVtOAtDhJeoEMtH0add0EeG5183HQCUt7yvMh2w1yTr99E6ldzsfv31vO71yfGmMmVJtSuPIpf0add0kounVT0x20slash0BhkDmMTBpPrWBypVIraSzwfiw2X97K0add0U2RcDteGmougFOtB3cqtRoIdfQ0xQT7lP6IP4PQcOfs4fCqpiro0add0uCvrN1D3eA2HBcaCx6Mkd59J2VzpWyQJOqXE0slash0vVQL0add0BMFkWD2lEUaSoqdUFTSs0equals0

**Comment by starlying** [comment]
可以试试stl:pageSqlContents标签

**Comment by kolostef** [comment]
解决了，小错误导致的应该加 <stl:dynamic> 。这个page标签强制用这个

**Comment by kolostef** [comment]
Leave a comment
