### ISSUE TITLE
升级到最新版本，原有限制数字标签出现了问题。

### ISSUE THREAD

**Issue by jiangbin4586** [siteserver/cms#845]
升级到最新版以后标签解析出问题了。
            <stl:contents channelName="论坛简介" totalNum="1" >
              <stl:content type="Content"></stl:content>
              <stl:a class="hmc2_m">更多>></stl:a>
            </stl:contents>
以上标签能正常解析，但不能限制文章字数.导致更多看不见了。标签没问题。
            <stl:contents channelName="论坛简介" totalNum="1" >
              <stl:content type="Content" wordNum="150"></stl:content>
              <stl:a class="hmc2_m">更多>></stl:a>
            </stl:contents>
上面加入了限制字数标签，就不能正常显示了.会把```<p style="text-indent: 2em;">```等所有html标签都显示出来. 标签有问题，现在需要修复这个问题。
             <stl:contents channelName="论坛简介" totalNum="1" >
              <stl:content type="Content" wordNum="150" isClearTags="true"></stl:content>
              <stl:a class="hmc2_m">更多>></stl:a>
            </stl:contents>
加入了去格式，确实正常可以去掉，但就不是原有样式了。标签没问题。

**Comment by starlying** [comment]
我们确认一下

**Comment by guodongme123** [comment]
content标签里wordNum属性确实有这个问题，还没解决
