### ISSUE TITLE
安装成功后，用链接进入后台，显示值不能为 null。参数名: key

### ISSUE THREAD

**Issue by x-manJS** [siteserver/cms#9]
系统 win10
数据MSSQL
安装成功后，用链接进入后台，错误显示值不能为 null。参数名: key
数据库都有表了
在basePage.cs文件68行报错。
请问知道是什么原因吗。

另外，siteserver文件夹里的原文件暂时没有开源的计划吗？

**Comment by x-manJS** [comment]
siteserver文件夹里的aspx文件应该是在siteserver.backgrouppage dll吧？

**Comment by x-manJS** [comment]
已解决

**Comment by starlying** [comment]
好的，aspx文件都在SiteServer.API项目里面

**Comment by ShaoYaoHua** [comment]
显示值不能为 null。参数名: key 这个咋解决的？麻烦能说下么

**Comment by x-manJS** [comment]
web.config 中的appSettings节点添加
`    <add key="PageInspector:ServerCodeMappingSupport" value="Disabled" />`

**Comment by starlying** [comment]
加到代码库了，感谢分享

**Comment by zhengeili** [comment]
感谢 ! 我差点又要重装一遍了 哈哈。 话说 加上这句 是起到做什么作用的呢？
