### ISSUE TITLE
6.3.12 Tags 结果页如何引用？在线等，急！谢谢！

### ISSUE THREAD

**Issue by 33vonon** [siteserver/cms#920]
![image](https://user-images.githubusercontent.com/39148510/41816841-d230a5a2-77c1-11e8-8aa4-35b4a13b4f91.png)

我在utils目录下建了一个tags.html
里面内容如下：
![image](https://user-images.githubusercontent.com/39148510/41816951-248a367c-77c4-11e8-8209-642c04829ce2.png)

通过标签点开结果页，就是乱码，是我写的方式不对么？到底要怎么写？我只查到了标签如何引用，但没有描述标签结果页如何引用的文档。

**Comment by 33vonon** [comment]
![image](https://user-images.githubusercontent.com/39148510/41816911-35ada246-77c3-11e8-9cf4-3a71fb40b370.png)

**Comment by 33vonon** [comment]
![image](https://user-images.githubusercontent.com/39148510/41816919-6082a14c-77c3-11e8-9d27-015f6d90cf50.png)

**Comment by xelnage** [comment]
设定文档的字符编码为utf-8试试

**Comment by 33vonon** [comment]
include引用的header里已经设置了编码格式，主要是底下的stl也没有识别成html。不知道怎么弄得。

**Comment by xelnage** [comment]
![image](https://user-images.githubusercontent.com/5657596/41817151-ceb56e02-77c7-11e8-97d0-3be2edd0729b.png) 这部分生成是失败的看后台错误日志里有没有信息.

还有你的分页要包含在 <stl:pageItems></stl:pageItems>里

**Comment by 33vonon** [comment]
我在别的页面也有引用分页，这样写应该也没什么大问题吧。。反正能实现。。。。。@starlying 
tags.html是手动创建.html文件还是。添加栏目模板还是内容模板还是单页模板？还有啥不对的地方啊？
