### ISSUE TITLE
如何使用自己保存的站点模板?

### ISSUE THREAD

**Issue by thingpower** [siteserver/cms#958]
问题如标题，安装了最新的6.4.1版，自己在原来系统的后台中用系统站点管理功能将网站保存为站点模板，然后在新版系统中新建了一个空站点，但在站点模板管理中导入站点模板操作后没有效果，是我操作有误还是有什么问题？

**Comment by starlying** [comment]
看看是不是新建站点后没有生成页面？

**Comment by thingpower** [comment]
试了一下，无效
我可能没说清楚，我导入站点模板后，在站点模板管理页面中看不到上传的模板

**Comment by starlying** [comment]
那会不会保存站点的时候没有选择保存文件？
