### ISSUE TITLE
安装之后进入后台重复安装

### ISSUE THREAD

**Issue by kecilly** [siteserver/cms#99]
我在安装后选择
是否加密连接字符串中的加密选项成功后进入后台再次进入到安装页
而选择不加密成功后进入后台则可以正常进入创建站点
建议在BaiRong.Core.WebConfigUtils中Load
 DatabaseType = EDatabaseTypeUtils.GetEnumType(databaseType);
            ConnectionString = connectionString;
            if (string.IsNullOrEmpty(AdminDirectory))
            {
                AdminDirectory = "siteserver";
            }
            if (string.IsNullOrEmpty(SecretKey))
            {
                SecretKey = "vEnfkn16t8aeaZKG3a4Gl9UUlzf4vgqU9xwh8ZV5";
            }
调整下位置
改为
if (string.IsNullOrEmpty(AdminDirectory))
            {
                AdminDirectory = "siteserver";
            }
            if (string.IsNullOrEmpty(SecretKey))
            {
                SecretKey = "vEnfkn16t8aeaZKG3a4Gl9UUlzf4vgqU9xwh8ZV5";
            }
            DatabaseType = EDatabaseTypeUtils.GetEnumType(databaseType);
            ConnectionString = connectionString;

**Comment by stuyun** [comment]
你的标题该改一下改成数据库字符串加密 导致解密失败 安装失败，解密的时候解密字符串 背放到后面去了
